2022-07-02 16:26:22.438 | ERROR    | app_doc.views:doc:1075 - Collection browsing error
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe32ef6d048>
    └ <Thread(Thread-1635, started daemon 140613436049152)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe32ef6cd90>
    └ <Thread(Thread-1635, started daemon 140613436049152)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1635, started daemon 140613436049152)>
    │    │        │    └ (<socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-1635, started daemon 140613436049152)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fe3283d40f0>>
    └ <Thread(Thread-1635, started daemon 140613436049152)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 48976)
    │    │              └ <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fe327f05268>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe3283d40f0>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fe3283d40f0>
    │    │                   │        └ ('127.0.0.1', 48976)
    │    │                   └ <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe3283d40f0>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fe326d037b8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe31cc04e10>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fe326d03840>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe31cc04e10>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fe326d01d08>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe3283d40f0>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe31cc04e10>
    │       └ <function BaseHandler.run at 0x7fe326cffa60>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fe31ce3f240>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fe326cffd90>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fe31ce3f240>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fe31ce3f240>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe31ffde128>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fe31ce3f240>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │    └ <function BaseHandler.get_response at 0x7fe326d33f28>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe31ffde128>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-21/doc-273/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9ad90>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe31ffde128>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fe31ffc3a20>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9ad08>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fe31ffc3a20>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fe31ffc3c50>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9ac80>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fe31ffc3c50>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fe31ffc3ef0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9abf8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fe31ffc3ef0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7fe31ffcfa20>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9ab70>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7fe31ffcfa20>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fe324ba2630>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9aae8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fe324ba2630>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fe324ba24e0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9aa60>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fe324ba24e0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fe324ba2588>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9a9d8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fe324ba2588>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fe324ba2550>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9a950>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fe324ba2550>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fe324ba2438>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9a8c8>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fe324ba2438>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fe324b926a0>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │    └ <function BaseHandler._get_response at 0x7fe31fffce18>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fe324b926a0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fe31ffde128>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 21, 'doc_id': 273}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <function doc at 0x7fe324a4e1e0>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 21, 'doc_id': 273}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-21/doc-273/'>
           └ <function doc at 0x7fe324a4e158>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 273
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fe326e04c88>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 273, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fe327fbfe18>
                   └ <django.db.models.manager.Manager object at 0x7fe3240f1278>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-07-02 21:37:59.757 | ERROR    | app_doc.views:doc:1075 - Collection browsing error
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe32ef6d048>
    └ <Thread(Thread-2331, started daemon 140613448636160)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe32ef6cd90>
    └ <Thread(Thread-2331, started daemon 140613448636160)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-2331, started daemon 140613448636160)>
    │    │        │    └ (<socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-2331, started daemon 140613448636160)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fe3283d40f0>>
    └ <Thread(Thread-2331, started daemon 140613448636160)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 51204)
    │    │              └ <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fe327f05268>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe3283d40f0>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fe3283d40f0>
    │    │                   │        └ ('127.0.0.1', 51204)
    │    │                   └ <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe3283d40f0>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fe326d037b8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe31deab780>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fe326d03840>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe31deab780>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fe326d01d08>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe3283d40f0>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe31deab780>
    │       └ <function BaseHandler.run at 0x7fe326cffa60>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fe327c4b6a0>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fe326cffd90>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fe327c4b6a0>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fe327c4b6a0>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe31ffde128>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fe327c4b6a0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               │    └ <function BaseHandler.get_response at 0x7fe326d33f28>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe31ffde128>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-21/doc-777/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9ad90>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe31ffde128>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fe31ffc3a20>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9ad08>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fe31ffc3a20>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fe31ffc3c50>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9ac80>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fe31ffc3c50>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fe31ffc3ef0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9abf8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fe31ffc3ef0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7fe31ffcfa20>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9ab70>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7fe31ffcfa20>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fe324ba2630>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9aae8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fe324ba2630>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fe324ba24e0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9aa60>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fe324ba24e0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fe324ba2588>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9a9d8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fe324ba2588>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fe324ba2550>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9a950>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fe324ba2550>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fe324ba2438>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9a8c8>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fe324ba2438>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fe324b926a0>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               │    └ <function BaseHandler._get_response at 0x7fe31fffce18>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fe324b926a0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fe31ffde128>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 21, 'doc_id': 777}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-21/doc-777/'>
               └ <function doc at 0x7fe324a4e1e0>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 21, 'doc_id': 777}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-21/doc-777/'>
           └ <function doc at 0x7fe324a4e158>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 777
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fe326e04c88>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 777, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fe327fbfe18>
                   └ <django.db.models.manager.Manager object at 0x7fe3240f1278>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-07-03 00:22:26.225 | ERROR    | app_doc.views:doc:1075 - Collection browsing error
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe32ef6d048>
    └ <Thread(Thread-2366, started daemon 140613448636160)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe32ef6cd90>
    └ <Thread(Thread-2366, started daemon 140613448636160)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-2366, started daemon 140613448636160)>
    │    │        │    └ (<socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-2366, started daemon 140613448636160)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fe3283d40f0>>
    └ <Thread(Thread-2366, started daemon 140613448636160)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 51680)
    │    │              └ <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fe327f05268>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe3283d40f0>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fe3283d40f0>
    │    │                   │        └ ('127.0.0.1', 51680)
    │    │                   └ <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe3283d40f0>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fe326d037b8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe31df16358>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fe326d03840>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe31df16358>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fe326d01d08>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe3283d40f0>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe31df16358>
    │       └ <function BaseHandler.run at 0x7fe326cffa60>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fe31cc19f28>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fe326cffd90>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fe31cc19f28>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fe31cc19f28>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe31ffde128>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fe31cc19f28>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               │    └ <function BaseHandler.get_response at 0x7fe326d33f28>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe31ffde128>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-43/doc-775/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9ad90>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe31ffde128>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fe31ffc3a20>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9ad08>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fe31ffc3a20>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fe31ffc3c50>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9ac80>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fe31ffc3c50>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fe31ffc3ef0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9abf8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fe31ffc3ef0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7fe31ffcfa20>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9ab70>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7fe31ffcfa20>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fe324ba2630>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9aae8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fe324ba2630>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fe324ba24e0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9aa60>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fe324ba24e0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fe324ba2588>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9a9d8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fe324ba2588>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fe324ba2550>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9a950>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fe324ba2550>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fe324ba2438>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9a8c8>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fe324ba2438>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fe324b926a0>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               │    └ <function BaseHandler._get_response at 0x7fe31fffce18>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fe324b926a0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fe31ffde128>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 43, 'doc_id': 775}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-43/doc-775/'>
               └ <function doc at 0x7fe324a4e1e0>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 43, 'doc_id': 775}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-43/doc-775/'>
           └ <function doc at 0x7fe324a4e158>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 775
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fe326e04c88>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 775, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fe327fbfe18>
                   └ <django.db.models.manager.Manager object at 0x7fe3240f1278>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-07-03 07:01:30.353 | ERROR    | app_doc.views:doc:1075 - 文集浏览出错
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe32ef6d048>
    └ <Thread(Thread-2442, started daemon 140613198542592)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe32ef6cd90>
    └ <Thread(Thread-2442, started daemon 140613198542592)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-2442, started daemon 140613198542592)>
    │    │        │    └ (<socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-2442, started daemon 140613198542592)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fe3283d40f0>>
    └ <Thread(Thread-2442, started daemon 140613198542592)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 52834)
    │    │              └ <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fe327f05268>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe3283d40f0>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fe3283d40f0>
    │    │                   │        └ ('127.0.0.1', 52834)
    │    │                   └ <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe3283d40f0>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fe326d037b8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe31e107a58>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fe326d03840>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe31e107a58>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fe326d01d08>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe3283d40f0>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe31e107a58>
    │       └ <function BaseHandler.run at 0x7fe326cffa60>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fe31df23cf8>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fe326cffd90>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fe31df23cf8>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fe31df23cf8>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe31ffde128>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fe31df23cf8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │    └ <function BaseHandler.get_response at 0x7fe326d33f28>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe31ffde128>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-21/doc-273/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9ad90>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe31ffde128>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fe31ffc3a20>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9ad08>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fe31ffc3a20>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fe31ffc3c50>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9ac80>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fe31ffc3c50>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fe31ffc3ef0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9abf8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fe31ffc3ef0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7fe31ffcfa20>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9ab70>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7fe31ffcfa20>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fe324ba2630>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9aae8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fe324ba2630>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fe324ba24e0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9aa60>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fe324ba24e0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fe324ba2588>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9a9d8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fe324ba2588>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fe324ba2550>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9a950>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fe324ba2550>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fe324ba2438>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9a8c8>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fe324ba2438>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fe324b926a0>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │    └ <function BaseHandler._get_response at 0x7fe31fffce18>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fe324b926a0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fe31ffde128>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 21, 'doc_id': 273}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <function doc at 0x7fe324a4e1e0>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 21, 'doc_id': 273}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-21/doc-273/'>
           └ <function doc at 0x7fe324a4e158>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 273
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fe326e04c88>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 273, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fe327fbfe18>
                   └ <django.db.models.manager.Manager object at 0x7fe3240f1278>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-07-03 09:42:15.137 | ERROR    | app_doc.views:doc:1075 - 文集浏览出错
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe32ef6d048>
    └ <Thread(Thread-2500, started daemon 140613198542592)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe32ef6cd90>
    └ <Thread(Thread-2500, started daemon 140613198542592)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-2500, started daemon 140613198542592)>
    │    │        │    └ (<socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-2500, started daemon 140613198542592)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fe3283d40f0>>
    └ <Thread(Thread-2500, started daemon 140613198542592)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 53324)
    │    │              └ <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fe327f05268>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe3283d40f0>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fe3283d40f0>
    │    │                   │        └ ('127.0.0.1', 53324)
    │    │                   └ <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe3283d40f0>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fe326d037b8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe31cc19f98>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fe326d03840>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe31cc19f98>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fe326d01d08>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe3283d40f0>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe31cc19f98>
    │       └ <function BaseHandler.run at 0x7fe326cffa60>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fe31dea3c88>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fe326cffd90>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fe31dea3c88>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fe31dea3c88>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe31ffde128>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fe31dea3c88>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-512/'>
               │    └ <function BaseHandler.get_response at 0x7fe326d33f28>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe31ffde128>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-34/doc-512/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9ad90>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe31ffde128>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-512/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fe31ffc3a20>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-512/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9ad08>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fe31ffc3a20>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-512/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fe31ffc3c50>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-512/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9ac80>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fe31ffc3c50>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-512/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fe31ffc3ef0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-512/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9abf8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fe31ffc3ef0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-512/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7fe31ffcfa20>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-512/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9ab70>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7fe31ffcfa20>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-512/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fe324ba2630>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-512/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9aae8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fe324ba2630>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-512/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fe324ba24e0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-512/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9aa60>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fe324ba24e0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-512/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fe324ba2588>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-512/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9a9d8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fe324ba2588>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-512/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fe324ba2550>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-512/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9a950>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fe324ba2550>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-512/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fe324ba2438>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-512/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9a8c8>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fe324ba2438>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-512/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fe324b926a0>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-512/'>
               │    └ <function BaseHandler._get_response at 0x7fe31fffce18>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fe324b926a0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-512/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fe31ffde128>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 34, 'doc_id': 512}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-34/doc-512/'>
               └ <function doc at 0x7fe324a4e1e0>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 34, 'doc_id': 512}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-34/doc-512/'>
           └ <function doc at 0x7fe324a4e158>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 512
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fe326e04c88>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 512, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fe327fbfe18>
                   └ <django.db.models.manager.Manager object at 0x7fe3240f1278>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
