2021-07-29 17:12:25.932 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-28_1649030.15704050584702112.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-28_1649030.15704050584702112.png?",)
2021-07-29 17:12:25.959 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1707350.2864095646869024.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1707350.2864095646869024.png?",)
2021-07-29 17:12:25.980 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1710410.7268898193128783.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1710410.7268898193128783.png?",)
2021-07-29 17:12:40.545 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-28_1649030.15704050584702112.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-28_1649030.15704050584702112.png?",)
2021-07-29 17:12:41.086 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1707350.2864095646869024.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1707350.2864095646869024.png?",)
2021-07-29 17:12:41.099 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1710410.7268898193128783.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1710410.7268898193128783.png?",)
2021-07-29 17:12:45.990 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1707350.2864095646869024.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1707350.2864095646869024.png?",)
2021-07-29 17:12:45.997 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-28_1649030.15704050584702112.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-28_1649030.15704050584702112.png?",)
2021-07-29 17:12:46.017 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1710410.7268898193128783.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1710410.7268898193128783.png?",)
2021-07-29 17:12:46.035 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-28_1717200.8508396937310263.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-28_1717200.8508396937310263.png?",)
2021-07-29 17:12:46.055 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1028090.24429923051565483.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1028090.24429923051565483.png?",)
2021-07-29 17:12:46.085 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1137300.5816776400600694.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1137300.5816776400600694.png?",)
2021-07-29 17:12:46.091 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1051260.7361479512008406.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1051260.7361479512008406.png?",)
2021-07-29 17:12:46.110 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1436240.5522429648167162.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1436240.5522429648167162.png?",)
2021-07-29 17:12:46.150 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1439560.29372264905797085.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1439560.29372264905797085.png?",)
2021-07-29 17:12:46.266 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1446130.0976090829432632.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1446130.0976090829432632.png?",)
2021-07-29 17:12:46.313 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1528120.7520437480289052.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1528120.7520437480289052.png?",)
2021-07-29 21:23:43.167 | ERROR    | app_doc.views:doc:1022 - 文集浏览出错
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f1ef4436378>
    └ <Thread(Thread-535, started daemon 139770583840512)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f1ef4436158>
    └ <Thread(Thread-535, started daemon 139770583840512)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-535, started daemon 139770583840512)>
    │    │        │    └ (<socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-535, started daemon 139770583840512)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7f1eee4e1eb8>>
    └ <Thread(Thread-535, started daemon 139770583840512)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 55122)
    │    │              └ <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7f1eedfeee18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f1eee4e1eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7f1eee4e1eb8>
    │    │                   │        └ ('127.0.0.1', 55122)
    │    │                   └ <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f1eee4e1eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7f1eed09ab70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f1ee4063278>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7f1eed09abf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f1ee4063278>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7f1eed09a0d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7f1eee4e1eb8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f1ee4063278>
    │       └ <function BaseHandler.run at 0x7f1eed091d90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f1ee40da828>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7f1eed097158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7f1ee40da828>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7f1ee40da828>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f1ee7a84b38>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f1ee40da828>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-23/doc-70/'>
               │    └ <function BaseHandler.get_response at 0x7f1eed221840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f1ee7a84b38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-23/doc-70/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1ee62cb510>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f1ee7a84b38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-23/doc-70/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7f1ee637b588>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-23/doc-70/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1ee62cb488>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7f1ee637b588>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-23/doc-70/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f1ee637bef0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-23/doc-70/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1ee62cb400>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f1ee637bef0>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-23/doc-70/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7f1ee6387da0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-23/doc-70/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1ee62cb378>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7f1ee6387da0>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-23/doc-70/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7f1ee79c0c50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-23/doc-70/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1ee62cb2f0>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7f1ee79c0c50>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-23/doc-70/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f1ee6dfa7f0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-23/doc-70/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1ee62cb268>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f1ee6dfa7f0>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-23/doc-70/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f1ee6dfa908>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-23/doc-70/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1ee62cb1e0>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f1ee6dfa908>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-23/doc-70/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f1ee6dfa860>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-23/doc-70/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1ee62cb158>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f1ee6dfa860>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-23/doc-70/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f1ee707ceb8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-23/doc-70/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1ee62cb0d0>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f1ee707ceb8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-23/doc-70/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f1ee707cf98>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-23/doc-70/'>
               │    └ <function BaseHandler._get_response at 0x7f1ee63b67b8>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f1ee707cf98>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-23/doc-70/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7f1ee7a84b38>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 23, 'doc_id': 70}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-23/doc-70/'>
               └ <function doc at 0x7f1ee6ca2048>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 23, 'doc_id': 70}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-23/doc-70/'>
           └ <function doc at 0x7f1ee6c9ff28>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 949, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 70
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7f1eed1ab048>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 70, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7f1eee0b68c8>
                   └ <django.db.models.manager.Manager object at 0x7f1ee6468f98>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2021-07-30 07:52:08.169 | ERROR    | app_doc.views:doc:1022 - 文集浏览出错
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f1ef4436378>
    └ <Thread(Thread-678, started daemon 139770583840512)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f1ef4436158>
    └ <Thread(Thread-678, started daemon 139770583840512)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-678, started daemon 139770583840512)>
    │    │        │    └ (<socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-678, started daemon 139770583840512)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7f1eee4e1eb8>>
    └ <Thread(Thread-678, started daemon 139770583840512)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 56026)
    │    │              └ <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7f1eedfeee18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f1eee4e1eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7f1eee4e1eb8>
    │    │                   │        └ ('127.0.0.1', 56026)
    │    │                   └ <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f1eee4e1eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7f1eed09ab70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f1edef2f3c8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7f1eed09abf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f1edef2f3c8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7f1eed09a0d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7f1eee4e1eb8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f1edef2f3c8>
    │       └ <function BaseHandler.run at 0x7f1eed091d90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f1edeefb668>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7f1eed097158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7f1edeefb668>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7f1edeefb668>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f1ee7a84b38>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f1edeefb668>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │    └ <function BaseHandler.get_response at 0x7f1eed221840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f1ee7a84b38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-22/doc-53/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1ee62cb510>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f1ee7a84b38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7f1ee637b588>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1ee62cb488>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7f1ee637b588>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f1ee637bef0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1ee62cb400>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f1ee637bef0>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7f1ee6387da0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1ee62cb378>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7f1ee6387da0>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7f1ee79c0c50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1ee62cb2f0>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7f1ee79c0c50>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f1ee6dfa7f0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1ee62cb268>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f1ee6dfa7f0>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f1ee6dfa908>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1ee62cb1e0>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f1ee6dfa908>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f1ee6dfa860>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1ee62cb158>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f1ee6dfa860>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f1ee707ceb8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1ee62cb0d0>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f1ee707ceb8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f1ee707cf98>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │    └ <function BaseHandler._get_response at 0x7f1ee63b67b8>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f1ee707cf98>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7f1ee7a84b38>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 22, 'doc_id': 53}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <function doc at 0x7f1ee6ca2048>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 22, 'doc_id': 53}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-22/doc-53/'>
           └ <function doc at 0x7f1ee6c9ff28>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 949, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 53
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7f1eed1ab048>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 53, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7f1eee0b68c8>
                   └ <django.db.models.manager.Manager object at 0x7f1ee6468f98>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2021-07-30 08:25:20.167 | ERROR    | app_doc.views:doc:1022 - 文集浏览出错
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f1ef4436378>
    └ <Thread(Thread-691, started daemon 139770583840512)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f1ef4436158>
    └ <Thread(Thread-691, started daemon 139770583840512)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-691, started daemon 139770583840512)>
    │    │        │    └ (<socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-691, started daemon 139770583840512)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7f1eee4e1eb8>>
    └ <Thread(Thread-691, started daemon 139770583840512)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 56080)
    │    │              └ <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7f1eedfeee18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f1eee4e1eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7f1eee4e1eb8>
    │    │                   │        └ ('127.0.0.1', 56080)
    │    │                   └ <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f1eee4e1eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7f1eed09ab70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f1ee4a5ea90>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7f1eed09abf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f1ee4a5ea90>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7f1eed09a0d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7f1eee4e1eb8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f1ee4a5ea90>
    │       └ <function BaseHandler.run at 0x7f1eed091d90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f1edeefb748>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7f1eed097158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7f1edeefb748>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7f1edeefb748>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f1ee7a84b38>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f1edeefb748>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-12/'>
               │    └ <function BaseHandler.get_response at 0x7f1eed221840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f1ee7a84b38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-1/doc-12/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1ee62cb510>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f1ee7a84b38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-12/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7f1ee637b588>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-12/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1ee62cb488>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7f1ee637b588>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-12/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f1ee637bef0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-12/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1ee62cb400>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f1ee637bef0>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-12/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7f1ee6387da0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-12/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1ee62cb378>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7f1ee6387da0>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-12/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7f1ee79c0c50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-12/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1ee62cb2f0>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7f1ee79c0c50>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-12/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f1ee6dfa7f0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-12/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1ee62cb268>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f1ee6dfa7f0>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-12/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f1ee6dfa908>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-12/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1ee62cb1e0>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f1ee6dfa908>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-12/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f1ee6dfa860>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-12/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1ee62cb158>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f1ee6dfa860>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-12/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f1ee707ceb8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-12/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1ee62cb0d0>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f1ee707ceb8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-12/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f1ee707cf98>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-12/'>
               │    └ <function BaseHandler._get_response at 0x7f1ee63b67b8>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f1ee707cf98>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-12/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7f1ee7a84b38>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 1, 'doc_id': 12}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-1/doc-12/'>
               └ <function doc at 0x7f1ee6ca2048>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 1, 'doc_id': 12}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-1/doc-12/'>
           └ <function doc at 0x7f1ee6c9ff28>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 949, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 12
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7f1eed1ab048>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 12, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7f1eee0b68c8>
                   └ <django.db.models.manager.Manager object at 0x7f1ee6468f98>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2021-07-30 08:29:30.308 | ERROR    | app_doc.views:doc:1022 - 文集浏览出错
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f1ef4436378>
    └ <Thread(Thread-693, started daemon 139770583840512)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f1ef4436158>
    └ <Thread(Thread-693, started daemon 139770583840512)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-693, started daemon 139770583840512)>
    │    │        │    └ (<socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-693, started daemon 139770583840512)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7f1eee4e1eb8>>
    └ <Thread(Thread-693, started daemon 139770583840512)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 56086)
    │    │              └ <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7f1eedfeee18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f1eee4e1eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7f1eee4e1eb8>
    │    │                   │        └ ('127.0.0.1', 56086)
    │    │                   └ <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f1eee4e1eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7f1eed09ab70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f1ee632e048>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7f1eed09abf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f1ee632e048>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7f1eed09a0d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7f1eee4e1eb8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f1ee632e048>
    │       └ <function BaseHandler.run at 0x7f1eed091d90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f1edee99f98>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7f1eed097158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7f1edee99f98>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7f1edee99f98>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f1ee7a84b38>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f1edee99f98>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │    └ <function BaseHandler.get_response at 0x7f1eed221840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f1ee7a84b38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-1/doc-161/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1ee62cb510>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f1ee7a84b38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7f1ee637b588>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1ee62cb488>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7f1ee637b588>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f1ee637bef0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1ee62cb400>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f1ee637bef0>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7f1ee6387da0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1ee62cb378>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7f1ee6387da0>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7f1ee79c0c50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1ee62cb2f0>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7f1ee79c0c50>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f1ee6dfa7f0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1ee62cb268>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f1ee6dfa7f0>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f1ee6dfa908>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1ee62cb1e0>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f1ee6dfa908>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f1ee6dfa860>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1ee62cb158>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f1ee6dfa860>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f1ee707ceb8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1ee62cb0d0>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f1ee707ceb8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f1ee707cf98>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │    └ <function BaseHandler._get_response at 0x7f1ee63b67b8>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f1ee707cf98>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7f1ee7a84b38>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 1, 'doc_id': 161}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <function doc at 0x7f1ee6ca2048>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 1, 'doc_id': 161}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-1/doc-161/'>
           └ <function doc at 0x7f1ee6c9ff28>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 949, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 161
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7f1eed1ab048>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 161, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7f1eee0b68c8>
                   └ <django.db.models.manager.Manager object at 0x7f1ee6468f98>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2021-07-30 08:33:45.404 | ERROR    | app_doc.views:doc:1022 - 文集浏览出错
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f1ef4436378>
    └ <Thread(Thread-695, started daemon 139770583840512)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f1ef4436158>
    └ <Thread(Thread-695, started daemon 139770583840512)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-695, started daemon 139770583840512)>
    │    │        │    └ (<socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-695, started daemon 139770583840512)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7f1eee4e1eb8>>
    └ <Thread(Thread-695, started daemon 139770583840512)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 56094)
    │    │              └ <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7f1eedfeee18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f1eee4e1eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7f1eee4e1eb8>
    │    │                   │        └ ('127.0.0.1', 56094)
    │    │                   └ <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f1eee4e1eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7f1eed09ab70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f1edee631d0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7f1eed09abf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f1edee631d0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7f1eed09a0d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7f1eee4e1eb8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f1edee631d0>
    │       └ <function BaseHandler.run at 0x7f1eed091d90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f1edee63358>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7f1eed097158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7f1edee63358>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7f1edee63358>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f1ee7a84b38>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f1edee63358>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-126/'>
               │    └ <function BaseHandler.get_response at 0x7f1eed221840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f1ee7a84b38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-1/doc-126/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1ee62cb510>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f1ee7a84b38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-126/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7f1ee637b588>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-126/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1ee62cb488>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7f1ee637b588>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-126/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f1ee637bef0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-126/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1ee62cb400>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f1ee637bef0>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-126/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7f1ee6387da0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-126/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1ee62cb378>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7f1ee6387da0>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-126/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7f1ee79c0c50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-126/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1ee62cb2f0>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7f1ee79c0c50>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-126/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f1ee6dfa7f0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-126/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1ee62cb268>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f1ee6dfa7f0>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-126/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f1ee6dfa908>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-126/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1ee62cb1e0>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f1ee6dfa908>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-126/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f1ee6dfa860>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-126/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1ee62cb158>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f1ee6dfa860>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-126/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f1ee707ceb8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-126/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1ee62cb0d0>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f1ee707ceb8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-126/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f1ee707cf98>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-126/'>
               │    └ <function BaseHandler._get_response at 0x7f1ee63b67b8>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f1ee707cf98>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-126/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7f1ee7a84b38>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 1, 'doc_id': 126}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-1/doc-126/'>
               └ <function doc at 0x7f1ee6ca2048>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 1, 'doc_id': 126}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-1/doc-126/'>
           └ <function doc at 0x7f1ee6c9ff28>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 949, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 126
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7f1eed1ab048>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 126, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7f1eee0b68c8>
                   └ <django.db.models.manager.Manager object at 0x7f1ee6468f98>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2021-07-30 11:24:27.250 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-28_1649030.15704050584702112.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-28_1649030.15704050584702112.png?",)
2021-07-30 11:24:27.255 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1707350.2864095646869024.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1707350.2864095646869024.png?",)
2021-07-30 11:24:27.266 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1710410.7268898193128783.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1710410.7268898193128783.png?",)
2021-07-30 11:24:27.277 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-28_1717200.8508396937310263.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-28_1717200.8508396937310263.png?",)
2021-07-30 11:24:27.288 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1028090.24429923051565483.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1028090.24429923051565483.png?",)
2021-07-30 11:24:27.298 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1051260.7361479512008406.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1051260.7361479512008406.png?",)
2021-07-30 11:24:27.308 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1137300.5816776400600694.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1137300.5816776400600694.png?",)
2021-07-30 11:24:27.319 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1436240.5522429648167162.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1436240.5522429648167162.png?",)
2021-07-30 11:24:27.331 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1439560.29372264905797085.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1439560.29372264905797085.png?",)
2021-07-30 11:24:27.343 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1446130.0976090829432632.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1446130.0976090829432632.png?",)
2021-07-30 11:24:27.354 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1528120.7520437480289052.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1528120.7520437480289052.png?",)
2021-07-30 11:39:36.738 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-28_1649030.15704050584702112.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-28_1649030.15704050584702112.png?",)
2021-07-30 11:39:36.758 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1707350.2864095646869024.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1707350.2864095646869024.png?",)
2021-07-30 11:39:36.778 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1028090.24429923051565483.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1028090.24429923051565483.png?",)
2021-07-30 11:39:36.794 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1051260.7361479512008406.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1051260.7361479512008406.png?",)
2021-07-30 11:39:36.810 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1446130.0976090829432632.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1446130.0976090829432632.png?",)
2021-07-30 11:39:36.826 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1528120.7520437480289052.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1528120.7520437480289052.png?",)
2021-07-30 11:39:36.843 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-28_1717200.8508396937310263.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-28_1717200.8508396937310263.png?",)
2021-07-30 11:39:36.859 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1710410.7268898193128783.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1710410.7268898193128783.png?",)
2021-07-30 11:39:36.877 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1137300.5816776400600694.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1137300.5816776400600694.png?",)
2021-07-30 11:39:36.893 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1436240.5522429648167162.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1436240.5522429648167162.png?",)
2021-07-30 11:39:36.910 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1439560.29372264905797085.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1439560.29372264905797085.png?",)
2021-07-30 11:48:34.998 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-28_1649030.15704050584702112.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-28_1649030.15704050584702112.png?",)
2021-07-30 11:48:35.020 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1137300.5816776400600694.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1137300.5816776400600694.png?",)
2021-07-30 11:48:35.051 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1707350.2864095646869024.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1707350.2864095646869024.png?",)
2021-07-30 11:48:35.055 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1710410.7268898193128783.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1710410.7268898193128783.png?",)
2021-07-30 11:48:35.072 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1436240.5522429648167162.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1436240.5522429648167162.png?",)
2021-07-30 11:48:35.089 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-28_1717200.8508396937310263.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-28_1717200.8508396937310263.png?",)
2021-07-30 11:48:35.106 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1028090.24429923051565483.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1028090.24429923051565483.png?",)
2021-07-30 11:48:35.123 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1051260.7361479512008406.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1051260.7361479512008406.png?",)
2021-07-30 11:48:35.140 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1439560.29372264905797085.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1439560.29372264905797085.png?",)
2021-07-30 11:48:35.157 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1446130.0976090829432632.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1446130.0976090829432632.png?",)
2021-07-30 11:48:35.174 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1528120.7520437480289052.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1528120.7520437480289052.png?",)
2021-07-30 11:49:42.075 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-28_1649030.15704050584702112.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-28_1649030.15704050584702112.png?",)
2021-07-30 11:49:42.113 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1707350.2864095646869024.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1707350.2864095646869024.png?",)
2021-07-30 11:49:42.138 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1710410.7268898193128783.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1710410.7268898193128783.png?",)
2021-07-30 11:49:42.151 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-28_1717200.8508396937310263.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-28_1717200.8508396937310263.png?",)
2021-07-30 11:49:42.170 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1028090.24429923051565483.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1028090.24429923051565483.png?",)
2021-07-30 11:49:42.187 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1051260.7361479512008406.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1051260.7361479512008406.png?",)
2021-07-30 11:49:42.199 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1436240.5522429648167162.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1436240.5522429648167162.png?",)
2021-07-30 11:49:42.214 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1439560.29372264905797085.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1439560.29372264905797085.png?",)
2021-07-30 11:49:42.228 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1446130.0976090829432632.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1446130.0976090829432632.png?",)
2021-07-30 11:49:42.240 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1528120.7520437480289052.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1528120.7520437480289052.png?",)
2021-07-30 11:49:42.255 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1137300.5816776400600694.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1137300.5816776400600694.png?",)
2021-07-30 11:51:13.985 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-28_1649030.15704050584702112.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-28_1649030.15704050584702112.png?",)
2021-07-30 11:51:13.998 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1707350.2864095646869024.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1707350.2864095646869024.png?",)
2021-07-30 11:51:14.015 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1710410.7268898193128783.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1710410.7268898193128783.png?",)
2021-07-30 11:51:14.034 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-28_1717200.8508396937310263.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-28_1717200.8508396937310263.png?",)
2021-07-30 11:51:14.050 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1028090.24429923051565483.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1028090.24429923051565483.png?",)
2021-07-30 11:51:14.064 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1051260.7361479512008406.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1051260.7361479512008406.png?",)
2021-07-30 11:51:14.084 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1137300.5816776400600694.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1137300.5816776400600694.png?",)
2021-07-30 11:51:14.097 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1436240.5522429648167162.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1436240.5522429648167162.png?",)
2021-07-30 11:51:14.109 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1439560.29372264905797085.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1439560.29372264905797085.png?",)
2021-07-30 11:51:14.121 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1446130.0976090829432632.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1446130.0976090829432632.png?",)
2021-07-30 11:51:14.134 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1528120.7520437480289052.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1528120.7520437480289052.png?",)
2021-07-30 11:52:58.380 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1137300.5816776400600694.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1137300.5816776400600694.png?",)
2021-07-30 11:52:58.390 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-28_1649030.15704050584702112.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-28_1649030.15704050584702112.png?",)
2021-07-30 11:52:58.407 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1028090.24429923051565483.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1028090.24429923051565483.png?",)
2021-07-30 11:52:58.418 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1051260.7361479512008406.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1051260.7361479512008406.png?",)
2021-07-30 11:52:58.431 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1707350.2864095646869024.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1707350.2864095646869024.png?",)
2021-07-30 11:52:58.444 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1710410.7268898193128783.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1710410.7268898193128783.png?",)
2021-07-30 11:52:58.456 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-28_1717200.8508396937310263.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-28_1717200.8508396937310263.png?",)
2021-07-30 11:52:58.470 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1436240.5522429648167162.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1436240.5522429648167162.png?",)
2021-07-30 11:52:58.483 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1528120.7520437480289052.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1528120.7520437480289052.png?",)
2021-07-30 11:52:58.495 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1446130.0976090829432632.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1446130.0976090829432632.png?",)
2021-07-30 11:52:58.507 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1439560.29372264905797085.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1439560.29372264905797085.png?",)
2021-07-30 15:18:12.562 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1051260.7361479512008406.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1051260.7361479512008406.png?",)
2021-07-30 15:18:12.572 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-28_1649030.15704050584702112.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-28_1649030.15704050584702112.png?",)
2021-07-30 15:18:12.588 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1710410.7268898193128783.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1710410.7268898193128783.png?",)
2021-07-30 15:18:12.601 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1707350.2864095646869024.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1707350.2864095646869024.png?",)
2021-07-30 15:18:12.617 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-28_1717200.8508396937310263.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-28_1717200.8508396937310263.png?",)
2021-07-30 15:18:12.630 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1137300.5816776400600694.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1137300.5816776400600694.png?",)
2021-07-30 15:18:12.646 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1436240.5522429648167162.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1436240.5522429648167162.png?",)
2021-07-30 15:18:12.660 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1439560.29372264905797085.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1439560.29372264905797085.png?",)
2021-07-30 15:18:12.674 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1446130.0976090829432632.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1446130.0976090829432632.png?",)
2021-07-30 15:18:12.687 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1528120.7520437480289052.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1528120.7520437480289052.png?",)
2021-07-30 15:18:12.702 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-29_1028090.24429923051565483.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-29_1028090.24429923051565483.png?",)
2021-07-30 16:48:28.492 | ERROR    | app_doc.views:doc:1022 - 文集浏览出错
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f1e414ad378>
    └ <Thread(Thread-239, started daemon 139767648032512)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f1e414ad158>
    └ <Thread(Thread-239, started daemon 139767648032512)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-239, started daemon 139767648032512)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-239, started daemon 139767648032512)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7f1e3b557eb8>>
    └ <Thread(Thread-239, started daemon 139767648032512)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 57920)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7f1e3b064e18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f1e3b557eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7f1e3b557eb8>
    │    │                   │        └ ('127.0.0.1', 57920)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f1e3b557eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7f1e3a110b70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f1e31855fd0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7f1e3a110bf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f1e31855fd0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7f1e3a1100d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7f1e3b557eb8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f1e31855fd0>
    │       └ <function BaseHandler.run at 0x7f1e3a108d90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f1e30802da0>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7f1e3a10d158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7f1e30802da0>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7f1e30802da0>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f1e38ad4e48>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f1e30802da0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-293/'>
               │    └ <function BaseHandler.get_response at 0x7f1e3a297840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f1e38ad4e48>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-21/doc-293/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1e333059d8>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f1e38ad4e48>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-293/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7f1e332a0240>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-293/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1e33305950>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7f1e332a0240>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-293/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f1e332a0710>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-293/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1e333058c8>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f1e332a0710>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-293/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7f1e332a0080>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-293/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1e33305840>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7f1e332a0080>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-293/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7f1e332a00b8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-293/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1e333057b8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7f1e332a00b8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-293/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f1e38079b38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-293/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1e33305730>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f1e38079b38>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-293/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f1e38079b70>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-293/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1e333056a8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f1e38079b70>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-293/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f1e38079c18>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-293/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1e33305620>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f1e38079c18>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-293/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f1e38079ac8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-293/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1e33305598>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f1e38079ac8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-293/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f1e38079b00>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-293/'>
               │    └ <function BaseHandler._get_response at 0x7f1e332e9ae8>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f1e38079b00>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-293/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7f1e38ad4e48>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 21, 'doc_id': 293}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-21/doc-293/'>
               └ <function doc at 0x7f1e33ce2510>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 21, 'doc_id': 293}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-21/doc-293/'>
           └ <function doc at 0x7f1e33ce2488>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 949, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 293
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7f1e3a221048>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 293, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7f1e3b12c8c8>
                   └ <django.db.models.manager.Manager object at 0x7f1e3346b630>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
