2022-07-16 16:04:53.418 | ERROR    | app_doc.views:doc:1075 - Collection browsing error
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f9d6a2aaea0>
    └ <Thread(Thread-138, started daemon 140313794029312)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f9d6a2aac80>
    └ <Thread(Thread-138, started daemon 140313794029312)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-138, started daemon 140313794029312)>
    │    │        │    └ (<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-138, started daemon 140313794029312)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7f9d63994f98>>
    └ <Thread(Thread-138, started daemon 140313794029312)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 40034)
    │    │              └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7f9d63244158>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f9d63994f98>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7f9d63994f98>
    │    │                   │        └ ('127.0.0.1', 40034)
    │    │                   └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f9d63994f98>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7f9d6203f598>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f9d59519e80>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7f9d6203f620>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f9d59519e80>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7f9d6203eae8>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7f9d63994f98>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f9d59519e80>
    │       └ <function BaseHandler.run at 0x7f9d62039840>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f9d59dfe278>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7f9d62039b70>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7f9d59dfe278>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7f9d59dfe278>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f9d60114d30>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f9d59dfe278>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-730/'>
               │    └ <function BaseHandler.get_response at 0x7f9d62072d08>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f9d60114d30>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-21/doc-730/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a7bf8>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f9d60114d30>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-730/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7f9d5b346da0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-730/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a7b70>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7f9d5b346da0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-730/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f9d5b3543c8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-730/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a7ae8>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f9d5b3543c8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-730/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7f9d5b354d68>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-730/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a7a60>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7f9d5b354d68>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-730/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7f9d5b354518>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-730/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a79d8>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7f9d5b354518>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-730/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7f9d5b2dee80>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-730/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a7950>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7f9d5b2dee80>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-730/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f9d60124860>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-730/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a78c8>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f9d60124860>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-730/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f9d60124940>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-730/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a7840>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f9d60124940>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-730/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f9d60124898>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-730/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a7620>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f9d60124898>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-730/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f9d60124828>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-730/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a7730>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f9d60124828>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-730/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f9d60bd7f98>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-730/'>
               │    └ <function BaseHandler._get_response at 0x7f9d5b2a76a8>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f9d60bd7f98>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-730/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7f9d60114d30>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 21, 'doc_id': 730}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-21/doc-730/'>
               └ <function doc at 0x7f9d5bd75048>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 21, 'doc_id': 730}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-21/doc-730/'>
           └ <function doc at 0x7f9d5bd71f28>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 730
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7f9d62142940>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 730, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7f9d632fdd08>
                   └ <django.db.models.manager.Manager object at 0x7f9d62045cc0>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 算法框架>, <Doc: TDH>, <Doc: 常用方法>, <Doc: Shell>, <Doc: 常用命令>, <Doc: 示例脚本>, <Doc: Redis>, <Doc: 常用...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-07-16 16:49:28.319 | ERROR    | app_doc.views:doc:1075 - Collection browsing error
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f9d6a2aaea0>
    └ <Thread(Thread-153, started daemon 140313794029312)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f9d6a2aac80>
    └ <Thread(Thread-153, started daemon 140313794029312)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-153, started daemon 140313794029312)>
    │    │        │    └ (<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-153, started daemon 140313794029312)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7f9d63994f98>>
    └ <Thread(Thread-153, started daemon 140313794029312)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 41346)
    │    │              └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7f9d63244158>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f9d63994f98>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7f9d63994f98>
    │    │                   │        └ ('127.0.0.1', 41346)
    │    │                   └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f9d63994f98>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7f9d6203f598>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f9d59336710>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7f9d6203f620>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f9d59336710>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7f9d6203eae8>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7f9d63994f98>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f9d59336710>
    │       └ <function BaseHandler.run at 0x7f9d62039840>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f9d59dd33c8>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7f9d62039b70>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7f9d59dd33c8>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7f9d59dd33c8>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f9d60114d30>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f9d59dd33c8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               │    └ <function BaseHandler.get_response at 0x7f9d62072d08>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f9d60114d30>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-34/doc-522/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a7bf8>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f9d60114d30>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7f9d5b346da0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a7b70>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7f9d5b346da0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f9d5b3543c8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a7ae8>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f9d5b3543c8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7f9d5b354d68>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a7a60>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7f9d5b354d68>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7f9d5b354518>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a79d8>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7f9d5b354518>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7f9d5b2dee80>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a7950>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7f9d5b2dee80>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f9d60124860>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a78c8>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f9d60124860>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f9d60124940>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a7840>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f9d60124940>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f9d60124898>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a7620>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f9d60124898>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f9d60124828>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a7730>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f9d60124828>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f9d60bd7f98>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               │    └ <function BaseHandler._get_response at 0x7f9d5b2a76a8>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f9d60bd7f98>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7f9d60114d30>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 34, 'doc_id': 522}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-34/doc-522/'>
               └ <function doc at 0x7f9d5bd75048>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 34, 'doc_id': 522}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-34/doc-522/'>
           └ <function doc at 0x7f9d5bd71f28>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 522
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7f9d62142940>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 522, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7f9d632fdd08>
                   └ <django.db.models.manager.Manager object at 0x7f9d62045cc0>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 算法框架>, <Doc: TDH>, <Doc: 常用方法>, <Doc: Shell>, <Doc: 常用命令>, <Doc: 示例脚本>, <Doc: Redis>, <Doc: 常用...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-07-17 00:33:49.066 | ERROR    | app_doc.views:doc:1075 - Collection browsing error
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f9d6a2aaea0>
    └ <Thread(Thread-467, started daemon 140313773573888)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f9d6a2aac80>
    └ <Thread(Thread-467, started daemon 140313773573888)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-467, started daemon 140313773573888)>
    │    │        │    └ (<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-467, started daemon 140313773573888)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7f9d63994f98>>
    └ <Thread(Thread-467, started daemon 140313773573888)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 43244)
    │    │              └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7f9d63244158>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f9d63994f98>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7f9d63994f98>
    │    │                   │        └ ('127.0.0.1', 43244)
    │    │                   └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f9d63994f98>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7f9d6203f598>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f9d5945ff28>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7f9d6203f620>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f9d5945ff28>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7f9d6203eae8>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7f9d63994f98>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f9d5945ff28>
    │       └ <function BaseHandler.run at 0x7f9d62039840>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f9d5b2aa9b0>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7f9d62039b70>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7f9d5b2aa9b0>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7f9d5b2aa9b0>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f9d60114d30>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f9d5b2aa9b0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-536/'>
               │    └ <function BaseHandler.get_response at 0x7f9d62072d08>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f9d60114d30>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-34/doc-536/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a7bf8>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f9d60114d30>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-536/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7f9d5b346da0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-536/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a7b70>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7f9d5b346da0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-536/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f9d5b3543c8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-536/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a7ae8>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f9d5b3543c8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-536/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7f9d5b354d68>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-536/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a7a60>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7f9d5b354d68>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-536/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7f9d5b354518>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-536/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a79d8>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7f9d5b354518>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-536/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7f9d5b2dee80>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-536/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a7950>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7f9d5b2dee80>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-536/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f9d60124860>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-536/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a78c8>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f9d60124860>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-536/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f9d60124940>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-536/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a7840>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f9d60124940>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-536/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f9d60124898>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-536/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a7620>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f9d60124898>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-536/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f9d60124828>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-536/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a7730>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f9d60124828>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-536/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f9d60bd7f98>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-536/'>
               │    └ <function BaseHandler._get_response at 0x7f9d5b2a76a8>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f9d60bd7f98>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-536/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7f9d60114d30>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 34, 'doc_id': 536}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-34/doc-536/'>
               └ <function doc at 0x7f9d5bd75048>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 34, 'doc_id': 536}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-34/doc-536/'>
           └ <function doc at 0x7f9d5bd71f28>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 536
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7f9d62142940>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 536, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7f9d632fdd08>
                   └ <django.db.models.manager.Manager object at 0x7f9d62045cc0>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 算法框架>, <Doc: TDH>, <Doc: 常用方法>, <Doc: Shell>, <Doc: 常用命令>, <Doc: 示例脚本>, <Doc: Redis>, <Doc: 常用...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-07-17 05:49:59.552 | ERROR    | app_doc.views:doc:1075 - 文集浏览出错
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f9d6a2aaea0>
    └ <Thread(Thread-549, started daemon 140313773573888)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f9d6a2aac80>
    └ <Thread(Thread-549, started daemon 140313773573888)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-549, started daemon 140313773573888)>
    │    │        │    └ (<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-549, started daemon 140313773573888)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7f9d63994f98>>
    └ <Thread(Thread-549, started daemon 140313773573888)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 44186)
    │    │              └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7f9d63244158>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f9d63994f98>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7f9d63994f98>
    │    │                   │        └ ('127.0.0.1', 44186)
    │    │                   └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f9d63994f98>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7f9d6203f598>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f9d593b0fd0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7f9d6203f620>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f9d593b0fd0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7f9d6203eae8>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7f9d63994f98>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f9d593b0fd0>
    │       └ <function BaseHandler.run at 0x7f9d62039840>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f9d5933fb00>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7f9d62039b70>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7f9d5933fb00>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7f9d5933fb00>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f9d60114d30>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f9d5933fb00>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               │    └ <function BaseHandler.get_response at 0x7f9d62072d08>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f9d60114d30>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-1/doc-289/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a7bf8>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f9d60114d30>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7f9d5b346da0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a7b70>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7f9d5b346da0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f9d5b3543c8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a7ae8>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f9d5b3543c8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7f9d5b354d68>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a7a60>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7f9d5b354d68>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7f9d5b354518>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a79d8>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7f9d5b354518>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7f9d5b2dee80>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a7950>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7f9d5b2dee80>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f9d60124860>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a78c8>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f9d60124860>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f9d60124940>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a7840>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f9d60124940>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f9d60124898>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a7620>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f9d60124898>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f9d60124828>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a7730>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f9d60124828>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f9d60bd7f98>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               │    └ <function BaseHandler._get_response at 0x7f9d5b2a76a8>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f9d60bd7f98>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7f9d60114d30>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 1, 'doc_id': 289}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-1/doc-289/'>
               └ <function doc at 0x7f9d5bd75048>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 1, 'doc_id': 289}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-1/doc-289/'>
           └ <function doc at 0x7f9d5bd71f28>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 289
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7f9d62142940>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 289, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7f9d632fdd08>
                   └ <django.db.models.manager.Manager object at 0x7f9d62045cc0>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 算法框架>, <Doc: TDH>, <Doc: 常用方法>, <Doc: Shell>, <Doc: 常用命令>, <Doc: 示例脚本>, <Doc: Redis>, <Doc: 常用...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-07-17 09:05:15.592 | ERROR    | app_doc.views:doc:1075 - Collection browsing error
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f9d6a2aaea0>
    └ <Thread(Thread-623, started daemon 140313773573888)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f9d6a2aac80>
    └ <Thread(Thread-623, started daemon 140313773573888)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-623, started daemon 140313773573888)>
    │    │        │    └ (<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-623, started daemon 140313773573888)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7f9d63994f98>>
    └ <Thread(Thread-623, started daemon 140313773573888)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 44794)
    │    │              └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7f9d63244158>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f9d63994f98>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7f9d63994f98>
    │    │                   │        └ ('127.0.0.1', 44794)
    │    │                   └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f9d63994f98>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7f9d6203f598>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f9d5950e550>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7f9d6203f620>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f9d5950e550>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7f9d6203eae8>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7f9d63994f98>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f9d5950e550>
    │       └ <function BaseHandler.run at 0x7f9d62039840>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f9d59dd33c8>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7f9d62039b70>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7f9d59dd33c8>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7f9d59dd33c8>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f9d60114d30>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f9d59dd33c8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-516/'>
               │    └ <function BaseHandler.get_response at 0x7f9d62072d08>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f9d60114d30>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-34/doc-516/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a7bf8>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f9d60114d30>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-516/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7f9d5b346da0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-516/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a7b70>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7f9d5b346da0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-516/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f9d5b3543c8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-516/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a7ae8>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f9d5b3543c8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-516/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7f9d5b354d68>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-516/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a7a60>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7f9d5b354d68>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-516/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7f9d5b354518>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-516/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a79d8>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7f9d5b354518>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-516/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7f9d5b2dee80>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-516/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a7950>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7f9d5b2dee80>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-516/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f9d60124860>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-516/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a78c8>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f9d60124860>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-516/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f9d60124940>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-516/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a7840>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f9d60124940>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-516/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f9d60124898>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-516/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a7620>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f9d60124898>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-516/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f9d60124828>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-516/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f9d5b2a7730>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f9d60124828>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-516/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f9d60bd7f98>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-516/'>
               │    └ <function BaseHandler._get_response at 0x7f9d5b2a76a8>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f9d60bd7f98>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-516/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7f9d60114d30>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 34, 'doc_id': 516}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-34/doc-516/'>
               └ <function doc at 0x7f9d5bd75048>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 34, 'doc_id': 516}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-34/doc-516/'>
           └ <function doc at 0x7f9d5bd71f28>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 516
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7f9d62142940>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 516, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7f9d632fdd08>
                   └ <django.db.models.manager.Manager object at 0x7f9d62045cc0>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 算法框架>, <Doc: TDH>, <Doc: 常用方法>, <Doc: Shell>, <Doc: 常用命令>, <Doc: 示例脚本>, <Doc: Redis>, <Doc: 常用...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
