2021-07-19 07:36:55.647 | ERROR    | app_doc.views:doc:1020 - 文集浏览出错
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f43fc333378>
    └ <Thread(Thread-533, started daemon 139929717774080)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f43fc333158>
    └ <Thread(Thread-533, started daemon 139929717774080)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-533, started daemon 139929717774080)>
    │    │        │    └ (<socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-533, started daemon 139929717774080)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7f43f63dedd8>>
    └ <Thread(Thread-533, started daemon 139929717774080)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 22184)
    │    │              └ <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7f43f5eebe18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f43f63dedd8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7f43f63dedd8>
    │    │                   │        └ ('127.0.0.1', 22184)
    │    │                   └ <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f43f63dedd8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7f43f4f97b70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f43ec7d8278>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7f43f4f97bf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f43ec7d8278>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7f43f4f970d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7f43f63dedd8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f43ec7d8278>
    │       └ <function BaseHandler.run at 0x7f43f4f8fd90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f43ec5beef0>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7f43f4f94158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7f43ec5beef0>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7f43ec5beef0>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f43ef97a630>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f43ec5beef0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               │    └ <function BaseHandler.get_response at 0x7f43f511e840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f43ef97a630>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-22/doc-85/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7f43ee1d6d08>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f43ef97a630>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7f43ee1fae10>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f43ee1d6c80>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7f43ee1fae10>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f43ee207c50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f43ee1d6bf8>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f43ee207c50>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7f43ee207c88>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f43ee1d6b70>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7f43ee207c88>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7f43ef8c0940>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f43ee1d6ae8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7f43ef8c0940>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f43eecec2e8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f43ee1d6a60>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f43eecec2e8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f43eecec400>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f43ee1d69d8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f43eecec400>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f43eecec358>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f43ee1d6950>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f43eecec358>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f43eef749b0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f43ee1d68c8>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f43eef749b0>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f43eef74a90>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               │    └ <function BaseHandler._get_response at 0x7f43ee1b6e18>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f43eef74a90>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7f43ef97a630>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 22, 'doc_id': 85}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-22/doc-85/'>
               └ <function doc at 0x7f43eeb93ae8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 22, 'doc_id': 85}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-22/doc-85/'>
           └ <function doc at 0x7f43eeb93a60>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 949, in doc
    project = Project.objects.get(id=int(pro_id))
              │       │                  └ 22
              │       └ <django.db.models.manager.ManagerDescriptor object at 0x7f43f5094978>
              └ <class 'app_doc.models.Project'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 22}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7f43f5fb38c8>
                   └ <django.db.models.manager.Manager object at 0x7f43ee2b02b0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Project'
    │    │     └ <Options for Project>
    │    └ <class 'app_doc.models.Project'>
    └ <QuerySet [<Project: About>, <Project: Algorithm Notebook>, <Project: Common Commands>, <Project: Machine Learning>, <Project...

app_doc.models.Project.DoesNotExist: Project matching query does not exist.
2021-07-19 12:57:33.653 | ERROR    | app_doc.views:doc:1020 - 文集浏览出错
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f43fc333378>
    └ <Thread(Thread-636, started daemon 139929631848192)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f43fc333158>
    └ <Thread(Thread-636, started daemon 139929631848192)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-636, started daemon 139929631848192)>
    │    │        │    └ (<socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-636, started daemon 139929631848192)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7f43f63dedd8>>
    └ <Thread(Thread-636, started daemon 139929631848192)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 22722)
    │    │              └ <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7f43f5eebe18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f43f63dedd8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7f43f63dedd8>
    │    │                   │        └ ('127.0.0.1', 22722)
    │    │                   └ <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f43f63dedd8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7f43f4f97b70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f43ec6de4a8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7f43f4f97bf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f43ec6de4a8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7f43f4f970d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7f43f63dedd8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f43ec6de4a8>
    │       └ <function BaseHandler.run at 0x7f43f4f8fd90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f43ec5beef0>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7f43f4f94158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7f43ec5beef0>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7f43ec5beef0>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f43ef97a630>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f43ec5beef0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-17/doc-42/'>
               │    └ <function BaseHandler.get_response at 0x7f43f511e840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f43ef97a630>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-17/doc-42/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7f43ee1d6d08>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f43ef97a630>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-17/doc-42/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7f43ee1fae10>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-17/doc-42/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f43ee1d6c80>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7f43ee1fae10>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-17/doc-42/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f43ee207c50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-17/doc-42/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f43ee1d6bf8>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f43ee207c50>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-17/doc-42/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7f43ee207c88>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-17/doc-42/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f43ee1d6b70>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7f43ee207c88>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-17/doc-42/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7f43ef8c0940>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-17/doc-42/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f43ee1d6ae8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7f43ef8c0940>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-17/doc-42/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f43eecec2e8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-17/doc-42/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f43ee1d6a60>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f43eecec2e8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-17/doc-42/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f43eecec400>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-17/doc-42/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f43ee1d69d8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f43eecec400>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-17/doc-42/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f43eecec358>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-17/doc-42/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f43ee1d6950>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f43eecec358>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-17/doc-42/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f43eef749b0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-17/doc-42/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f43ee1d68c8>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f43eef749b0>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-17/doc-42/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f43eef74a90>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-17/doc-42/'>
               │    └ <function BaseHandler._get_response at 0x7f43ee1b6e18>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f43eef74a90>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-17/doc-42/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7f43ef97a630>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 17, 'doc_id': 42}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-17/doc-42/'>
               └ <function doc at 0x7f43eeb93ae8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 17, 'doc_id': 42}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-17/doc-42/'>
           └ <function doc at 0x7f43eeb93a60>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 949, in doc
    project = Project.objects.get(id=int(pro_id))
              │       │                  └ 17
              │       └ <django.db.models.manager.ManagerDescriptor object at 0x7f43f5094978>
              └ <class 'app_doc.models.Project'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 17}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7f43f5fb38c8>
                   └ <django.db.models.manager.Manager object at 0x7f43ee2b02b0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Project'
    │    │     └ <Options for Project>
    │    └ <class 'app_doc.models.Project'>
    └ <QuerySet [<Project: About>, <Project: Algorithm Notebook>, <Project: Common Commands>, <Project: Machine Learning>, <Project...

app_doc.models.Project.DoesNotExist: Project matching query does not exist.
