2021-07-24 11:13:01.867 | ERROR    | app_doc.util_upload_img:url_img_upload:286 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202106/2021-06-13_103806.png': No schema supplied. Perhaps you meant http:///media/202106/2021-06-13_103806.png?",)
2021-07-24 11:13:01.889 | ERROR    | app_doc.util_upload_img:url_img_upload:286 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-24_102733.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-24_102733.png?",)
2021-07-24 11:13:03.800 | ERROR    | app_doc.util_upload_img:url_img_upload:286 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202106/2021-06-13_103806.png': No schema supplied. Perhaps you meant http:///media/202106/2021-06-13_103806.png?",)
2021-07-24 11:13:03.851 | ERROR    | app_doc.util_upload_img:url_img_upload:286 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-24_102733.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-24_102733.png?",)
2021-07-24 13:17:42.175 | ERROR    | app_doc.views:doc:1022 - 文集浏览出错
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fbaabd53378>
    └ <Thread(Thread-1795, started daemon 140439373993728)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fbaabd53158>
    └ <Thread(Thread-1795, started daemon 140439373993728)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1795, started daemon 140439373993728)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-1795, started daemon 140439373993728)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fbaa5dfde48>>
    └ <Thread(Thread-1795, started daemon 140439373993728)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 37678)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fbaa590ae18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbaa5dfde48>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fbaa5dfde48>
    │    │                   │        └ ('127.0.0.1', 37678)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbaa5dfde48>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fbaa49b6b70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fba9c05a128>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fbaa49b6bf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fba9c05a128>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fbaa49b60d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbaa5dfde48>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fba9c05a128>
    │       └ <function BaseHandler.run at 0x7fbaa49aed90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fba8d6279b0>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fbaa49b3158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fba8d6279b0>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fba8d6279b0>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fba9f398748>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fba8d6279b0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-231/'>
               │    └ <function BaseHandler.get_response at 0x7fbaa4b3d840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fba9f398748>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-21/doc-231/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23d90>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fba9f398748>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-231/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fba9dc45b38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-231/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23d08>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fba9dc45b38>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-231/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fba9dc51eb8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-231/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23c80>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fba9dc51eb8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-231/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fba9dc51908>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-231/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23bf8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fba9dc51908>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-231/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fba9e70c400>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-231/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23b70>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fba9e70c400>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-231/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fba9e70c518>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-231/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23ae8>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fba9e70c518>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-231/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fba9e70c470>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-231/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23a60>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fba9e70c470>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-231/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fba9dc5ec50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-231/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc239d8>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fba9dc5ec50>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-231/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fba9dc5e400>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-231/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23950>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fba9dc5e400>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-231/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fba9e993ac8>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-231/'>
               │    └ <function BaseHandler._get_response at 0x7fba9dc02ea0>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fba9e993ac8>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-231/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fba9f398748>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 21, 'doc_id': 231}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-21/doc-231/'>
               └ <function doc at 0x7fba9e5b1ae8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 21, 'doc_id': 231}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-21/doc-231/'>
           └ <function doc at 0x7fba9e5b1a60>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 949, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 231
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fbaa4abdf98>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 231, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fbaa59d28c8>
                   └ <django.db.models.manager.Manager object at 0x7fba9dd6d390>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2021-07-24 17:49:07.170 | ERROR    | app_doc.views:doc:1022 - 文集浏览出错
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fbaabd53378>
    └ <Thread(Thread-2560, started daemon 140439382386432)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fbaabd53158>
    └ <Thread(Thread-2560, started daemon 140439382386432)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-2560, started daemon 140439382386432)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-2560, started daemon 140439382386432)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fbaa5dfde48>>
    └ <Thread(Thread-2560, started daemon 140439382386432)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 39464)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fbaa590ae18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbaa5dfde48>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fbaa5dfde48>
    │    │                   │        └ ('127.0.0.1', 39464)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbaa5dfde48>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fbaa49b6b70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fba9c0bdb00>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fbaa49b6bf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fba9c0bdb00>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fbaa49b60d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbaa5dfde48>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fba9c0bdb00>
    │       └ <function BaseHandler.run at 0x7fbaa49aed90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fba9c087668>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fbaa49b3158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fba9c087668>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fba9c087668>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fba9f398748>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fba9c087668>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-8/'>
               │    └ <function BaseHandler.get_response at 0x7fbaa4b3d840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fba9f398748>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-1/doc-8/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23d90>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fba9f398748>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-8/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fba9dc45b38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-8/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23d08>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fba9dc45b38>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-8/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fba9dc51eb8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-8/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23c80>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fba9dc51eb8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-8/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fba9dc51908>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-8/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23bf8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fba9dc51908>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-8/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fba9e70c400>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-8/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23b70>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fba9e70c400>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-8/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fba9e70c518>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-8/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23ae8>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fba9e70c518>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-8/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fba9e70c470>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-8/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23a60>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fba9e70c470>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-8/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fba9dc5ec50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-8/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc239d8>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fba9dc5ec50>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-8/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fba9dc5e400>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-8/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23950>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fba9dc5e400>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-8/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fba9e993ac8>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-8/'>
               │    └ <function BaseHandler._get_response at 0x7fba9dc02ea0>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fba9e993ac8>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-8/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fba9f398748>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 1, 'doc_id': 8}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-1/doc-8/'>
               └ <function doc at 0x7fba9e5b1ae8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 1, 'doc_id': 8}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-1/doc-8/'>
           └ <function doc at 0x7fba9e5b1a60>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 949, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 8
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fbaa4abdf98>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 8, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fbaa59d28c8>
                   └ <django.db.models.manager.Manager object at 0x7fba9dd6d390>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2021-07-24 18:21:04.799 | ERROR    | app_doc.views:doc:1022 - 文集浏览出错
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fbaabd53378>
    └ <Thread(Thread-2568, started daemon 140439382386432)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fbaabd53158>
    └ <Thread(Thread-2568, started daemon 140439382386432)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-2568, started daemon 140439382386432)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-2568, started daemon 140439382386432)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fbaa5dfde48>>
    └ <Thread(Thread-2568, started daemon 140439382386432)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 39512)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fbaa590ae18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbaa5dfde48>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fbaa5dfde48>
    │    │                   │        └ ('127.0.0.1', 39512)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbaa5dfde48>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fbaa49b6b70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fba9c187d30>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fbaa49b6bf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fba9c187d30>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fbaa49b60d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbaa5dfde48>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fba9c187d30>
    │       └ <function BaseHandler.run at 0x7fbaa49aed90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fba96583ac8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fbaa49b3158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fba96583ac8>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fba96583ac8>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fba9f398748>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fba96583ac8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-17/doc-42/'>
               │    └ <function BaseHandler.get_response at 0x7fbaa4b3d840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fba9f398748>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-17/doc-42/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23d90>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fba9f398748>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-17/doc-42/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fba9dc45b38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-17/doc-42/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23d08>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fba9dc45b38>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-17/doc-42/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fba9dc51eb8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-17/doc-42/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23c80>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fba9dc51eb8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-17/doc-42/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fba9dc51908>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-17/doc-42/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23bf8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fba9dc51908>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-17/doc-42/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fba9e70c400>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-17/doc-42/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23b70>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fba9e70c400>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-17/doc-42/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fba9e70c518>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-17/doc-42/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23ae8>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fba9e70c518>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-17/doc-42/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fba9e70c470>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-17/doc-42/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23a60>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fba9e70c470>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-17/doc-42/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fba9dc5ec50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-17/doc-42/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc239d8>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fba9dc5ec50>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-17/doc-42/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fba9dc5e400>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-17/doc-42/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23950>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fba9dc5e400>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-17/doc-42/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fba9e993ac8>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-17/doc-42/'>
               │    └ <function BaseHandler._get_response at 0x7fba9dc02ea0>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fba9e993ac8>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-17/doc-42/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fba9f398748>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 17, 'doc_id': 42}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-17/doc-42/'>
               └ <function doc at 0x7fba9e5b1ae8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 17, 'doc_id': 42}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-17/doc-42/'>
           └ <function doc at 0x7fba9e5b1a60>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 949, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 42
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fbaa4abdf98>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 42, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fbaa59d28c8>
                   └ <django.db.models.manager.Manager object at 0x7fba9dd6d390>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2021-07-24 18:38:09.488 | ERROR    | app_doc.views:doc:1022 - 文集浏览出错
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fbaabd53378>
    └ <Thread(Thread-2577, started daemon 140439470565120)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fbaabd53158>
    └ <Thread(Thread-2577, started daemon 140439470565120)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-2577, started daemon 140439470565120)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-2577, started daemon 140439470565120)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fbaa5dfde48>>
    └ <Thread(Thread-2577, started daemon 140439470565120)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 39548)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fbaa590ae18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbaa5dfde48>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fbaa5dfde48>
    │    │                   │        └ ('127.0.0.1', 39548)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbaa5dfde48>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fbaa49b6b70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fba9c18d828>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fbaa49b6bf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fba9c18d828>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fbaa49b60d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbaa5dfde48>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fba9c18d828>
    │       └ <function BaseHandler.run at 0x7fbaa49aed90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fba9c217438>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fbaa49b3158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fba9c217438>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fba9c217438>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fba9f398748>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fba9c217438>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-127/'>
               │    └ <function BaseHandler.get_response at 0x7fbaa4b3d840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fba9f398748>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-1/doc-127/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23d90>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fba9f398748>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-127/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fba9dc45b38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-127/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23d08>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fba9dc45b38>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-127/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fba9dc51eb8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-127/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23c80>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fba9dc51eb8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-127/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fba9dc51908>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-127/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23bf8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fba9dc51908>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-127/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fba9e70c400>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-127/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23b70>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fba9e70c400>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-127/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fba9e70c518>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-127/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23ae8>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fba9e70c518>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-127/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fba9e70c470>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-127/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23a60>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fba9e70c470>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-127/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fba9dc5ec50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-127/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc239d8>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fba9dc5ec50>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-127/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fba9dc5e400>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-127/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23950>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fba9dc5e400>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-127/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fba9e993ac8>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-127/'>
               │    └ <function BaseHandler._get_response at 0x7fba9dc02ea0>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fba9e993ac8>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-127/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fba9f398748>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 1, 'doc_id': 127}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-1/doc-127/'>
               └ <function doc at 0x7fba9e5b1ae8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 1, 'doc_id': 127}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-1/doc-127/'>
           └ <function doc at 0x7fba9e5b1a60>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 949, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 127
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fbaa4abdf98>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 127, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fbaa59d28c8>
                   └ <django.db.models.manager.Manager object at 0x7fba9dd6d390>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2021-07-24 22:38:11.044 | ERROR    | app_doc.views:doc:1022 - 文集浏览出错
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fbaabd53378>
    └ <Thread(Thread-2629, started daemon 140439470565120)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fbaabd53158>
    └ <Thread(Thread-2629, started daemon 140439470565120)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-2629, started daemon 140439470565120)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-2629, started daemon 140439470565120)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fbaa5dfde48>>
    └ <Thread(Thread-2629, started daemon 140439470565120)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 39894)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fbaa590ae18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbaa5dfde48>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fbaa5dfde48>
    │    │                   │        └ ('127.0.0.1', 39894)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbaa5dfde48>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fbaa49b6b70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fba9c05a128>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fbaa49b6bf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fba9c05a128>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fbaa49b60d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbaa5dfde48>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fba9c05a128>
    │       └ <function BaseHandler.run at 0x7fbaa49aed90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fba9c0bdfd0>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fbaa49b3158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fba9c0bdfd0>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fba9c0bdfd0>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fba9f398748>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fba9c0bdfd0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-150/'>
               │    └ <function BaseHandler.get_response at 0x7fbaa4b3d840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fba9f398748>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-1/doc-150/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23d90>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fba9f398748>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-150/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fba9dc45b38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-150/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23d08>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fba9dc45b38>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-150/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fba9dc51eb8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-150/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23c80>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fba9dc51eb8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-150/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fba9dc51908>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-150/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23bf8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fba9dc51908>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-150/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fba9e70c400>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-150/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23b70>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fba9e70c400>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-150/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fba9e70c518>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-150/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23ae8>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fba9e70c518>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-150/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fba9e70c470>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-150/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23a60>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fba9e70c470>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-150/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fba9dc5ec50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-150/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc239d8>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fba9dc5ec50>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-150/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fba9dc5e400>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-150/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23950>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fba9dc5e400>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-150/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fba9e993ac8>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-150/'>
               │    └ <function BaseHandler._get_response at 0x7fba9dc02ea0>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fba9e993ac8>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-150/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fba9f398748>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 1, 'doc_id': 150}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-1/doc-150/'>
               └ <function doc at 0x7fba9e5b1ae8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 1, 'doc_id': 150}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-1/doc-150/'>
           └ <function doc at 0x7fba9e5b1a60>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 949, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 150
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fbaa4abdf98>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 150, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fbaa59d28c8>
                   └ <django.db.models.manager.Manager object at 0x7fba9dd6d390>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2021-07-25 02:16:35.788 | ERROR    | app_doc.views:doc:1022 - 文集浏览出错
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fbaabd53378>
    └ <Thread(Thread-2667, started daemon 140439470565120)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fbaabd53158>
    └ <Thread(Thread-2667, started daemon 140439470565120)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-2667, started daemon 140439470565120)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-2667, started daemon 140439470565120)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fbaa5dfde48>>
    └ <Thread(Thread-2667, started daemon 140439470565120)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 40166)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fbaa590ae18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbaa5dfde48>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fbaa5dfde48>
    │    │                   │        └ ('127.0.0.1', 40166)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbaa5dfde48>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fbaa49b6b70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fba8d6279b0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fbaa49b6bf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fba8d6279b0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fbaa49b60d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbaa5dfde48>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fba8d6279b0>
    │       └ <function BaseHandler.run at 0x7fbaa49aed90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fba965e2828>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fbaa49b3158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fba965e2828>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fba965e2828>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fba9f398748>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fba965e2828>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-293/'>
               │    └ <function BaseHandler.get_response at 0x7fbaa4b3d840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fba9f398748>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-21/doc-293/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23d90>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fba9f398748>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-293/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fba9dc45b38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-293/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23d08>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fba9dc45b38>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-293/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fba9dc51eb8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-293/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23c80>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fba9dc51eb8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-293/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fba9dc51908>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-293/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23bf8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fba9dc51908>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-293/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fba9e70c400>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-293/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23b70>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fba9e70c400>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-293/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fba9e70c518>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-293/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23ae8>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fba9e70c518>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-293/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fba9e70c470>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-293/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23a60>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fba9e70c470>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-293/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fba9dc5ec50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-293/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc239d8>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fba9dc5ec50>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-293/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fba9dc5e400>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-293/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23950>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fba9dc5e400>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-293/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fba9e993ac8>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-293/'>
               │    └ <function BaseHandler._get_response at 0x7fba9dc02ea0>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fba9e993ac8>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-293/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fba9f398748>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 21, 'doc_id': 293}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-21/doc-293/'>
               └ <function doc at 0x7fba9e5b1ae8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 21, 'doc_id': 293}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-21/doc-293/'>
           └ <function doc at 0x7fba9e5b1a60>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 949, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 293
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fbaa4abdf98>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 293, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fbaa59d28c8>
                   └ <django.db.models.manager.Manager object at 0x7fba9dd6d390>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2021-07-25 09:08:09.450 | ERROR    | app_doc.views:doc:1022 - 文集浏览出错
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fbaabd53378>
    └ <Thread(Thread-2779, started daemon 140439382386432)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fbaabd53158>
    └ <Thread(Thread-2779, started daemon 140439382386432)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-2779, started daemon 140439382386432)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-2779, started daemon 140439382386432)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fbaa5dfde48>>
    └ <Thread(Thread-2779, started daemon 140439382386432)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 40816)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fbaa590ae18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbaa5dfde48>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fbaa5dfde48>
    │    │                   │        └ ('127.0.0.1', 40816)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbaa5dfde48>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fbaa49b6b70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fba9c0bdfd0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fbaa49b6bf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fba9c0bdfd0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fbaa49b60d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbaa5dfde48>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fba9c0bdfd0>
    │       └ <function BaseHandler.run at 0x7fbaa49aed90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fba96323f98>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fbaa49b3158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fba96323f98>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fba96323f98>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fba9f398748>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fba96323f98>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-130/'>
               │    └ <function BaseHandler.get_response at 0x7fbaa4b3d840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fba9f398748>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-1/doc-130/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23d90>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fba9f398748>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-130/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fba9dc45b38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-130/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23d08>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fba9dc45b38>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-130/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fba9dc51eb8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-130/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23c80>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fba9dc51eb8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-130/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fba9dc51908>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-130/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23bf8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fba9dc51908>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-130/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fba9e70c400>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-130/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23b70>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fba9e70c400>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-130/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fba9e70c518>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-130/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23ae8>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fba9e70c518>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-130/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fba9e70c470>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-130/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23a60>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fba9e70c470>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-130/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fba9dc5ec50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-130/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc239d8>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fba9dc5ec50>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-130/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fba9dc5e400>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-130/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fba9dc23950>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fba9dc5e400>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-130/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fba9e993ac8>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-130/'>
               │    └ <function BaseHandler._get_response at 0x7fba9dc02ea0>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fba9e993ac8>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-130/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fba9f398748>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 1, 'doc_id': 130}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-1/doc-130/'>
               └ <function doc at 0x7fba9e5b1ae8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 1, 'doc_id': 130}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-1/doc-130/'>
           └ <function doc at 0x7fba9e5b1a60>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 949, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 130
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fbaa4abdf98>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 130, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fbaa59d28c8>
                   └ <django.db.models.manager.Manager object at 0x7fba9dd6d390>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
