2022-06-27 00:37:40.412 | ERROR    | app_doc.views:doc:1075 - 文集浏览出错
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe4d4679ea0>
    └ <Thread(Thread-5268, started daemon 140620468270848)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe4d4679c80>
    └ <Thread(Thread-5268, started daemon 140620468270848)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-5268, started daemon 140620468270848)>
    │    │        │    └ (<socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-5268, started daemon 140620468270848)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>>
    └ <Thread(Thread-5268, started daemon 140620468270848)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 42694)
    │    │              └ <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fe4cd612158>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
    │    │                   │        └ ('127.0.0.1', 42694)
    │    │                   └ <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fe4cc40e6a8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe4c2ccbba8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fe4cc40e730>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe4c2ccbba8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fe4cc40cbf8>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe4c2ccbba8>
    │       └ <function BaseHandler.run at 0x7fe4cc409950>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4c1c35160>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fe4cc409c80>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4c1c35160>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4c1c35160>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4c1c35160>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-137/'>
               │    └ <function BaseHandler.get_response at 0x7fe4cc440e18>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-1/doc-137/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969ec80>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-137/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fe4c974c320>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-137/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969ebf8>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fe4c974c320>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-137/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fe4c974c6d8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-137/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969eb70>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fe4c974c6d8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-137/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fe4c974cb70>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-137/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969eae8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fe4c974cb70>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-137/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7fe4c96d8630>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-137/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969ea60>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7fe4c96d8630>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-137/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fe4c96d84e0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-137/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e9d8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fe4c96d84e0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-137/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fe4ca2c1ac8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-137/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e950>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fe4ca2c1ac8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-137/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fe4ca2c1978>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-137/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e8c8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fe4ca2c1978>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-137/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fe4ca2c1a20>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-137/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e6a8>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fe4ca2c1a20>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-137/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fe4cae86908>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-137/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e7b8>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fe4cae86908>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-137/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fe4ca2adb70>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-137/'>
               │    └ <function BaseHandler._get_response at 0x7fe4c969e730>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fe4ca2adb70>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-137/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 1, 'doc_id': 137}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-1/doc-137/'>
               └ <function doc at 0x7fe4ca1700d0>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 1, 'doc_id': 137}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-1/doc-137/'>
           └ <function doc at 0x7fe4ca170048>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 137
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fe4cc510b00>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 137, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fe4cd6cbd08>
                   └ <django.db.models.manager.Manager object at 0x7fe4cc411e80>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-06-27 02:31:39.252 | ERROR    | app_doc.views:doc:1075 - Collection browsing error
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe4d4679ea0>
    └ <Thread(Thread-5292, started daemon 140620468270848)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe4d4679c80>
    └ <Thread(Thread-5292, started daemon 140620468270848)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-5292, started daemon 140620468270848)>
    │    │        │    └ (<socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-5292, started daemon 140620468270848)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>>
    └ <Thread(Thread-5292, started daemon 140620468270848)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 43010)
    │    │              └ <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fe4cd612158>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
    │    │                   │        └ ('127.0.0.1', 43010)
    │    │                   └ <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fe4cc40e6a8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe4c3e715c0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fe4cc40e730>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe4c3e715c0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fe4cc40cbf8>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe4c3e715c0>
    │       └ <function BaseHandler.run at 0x7fe4cc409950>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4c1b6cb00>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fe4cc409c80>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4c1b6cb00>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4c1b6cb00>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4c1b6cb00>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-292/'>
               │    └ <function BaseHandler.get_response at 0x7fe4cc440e18>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-1/doc-292/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969ec80>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-292/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fe4c974c320>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-292/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969ebf8>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fe4c974c320>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-292/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fe4c974c6d8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-292/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969eb70>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fe4c974c6d8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-292/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fe4c974cb70>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-292/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969eae8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fe4c974cb70>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-292/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7fe4c96d8630>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-292/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969ea60>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7fe4c96d8630>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-292/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fe4c96d84e0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-292/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e9d8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fe4c96d84e0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-292/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fe4ca2c1ac8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-292/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e950>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fe4ca2c1ac8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-292/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fe4ca2c1978>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-292/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e8c8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fe4ca2c1978>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-292/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fe4ca2c1a20>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-292/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e6a8>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fe4ca2c1a20>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-292/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fe4cae86908>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-292/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e7b8>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fe4cae86908>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-292/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fe4ca2adb70>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-292/'>
               │    └ <function BaseHandler._get_response at 0x7fe4c969e730>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fe4ca2adb70>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-292/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 1, 'doc_id': 292}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-1/doc-292/'>
               └ <function doc at 0x7fe4ca1700d0>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 1, 'doc_id': 292}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-1/doc-292/'>
           └ <function doc at 0x7fe4ca170048>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 292
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fe4cc510b00>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 292, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fe4cd6cbd08>
                   └ <django.db.models.manager.Manager object at 0x7fe4cc411e80>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-06-27 03:41:33.789 | ERROR    | app_doc.views:doc:1075 - 文集浏览出错
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe4d4679ea0>
    └ <Thread(Thread-5322, started daemon 140620488492800)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe4d4679c80>
    └ <Thread(Thread-5322, started daemon 140620488492800)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-5322, started daemon 140620488492800)>
    │    │        │    └ (<socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-5322, started daemon 140620488492800)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>>
    └ <Thread(Thread-5322, started daemon 140620488492800)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 43244)
    │    │              └ <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fe4cd612158>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
    │    │                   │        └ ('127.0.0.1', 43244)
    │    │                   └ <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fe4cc40e6a8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe4c368e438>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fe4cc40e730>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe4c368e438>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fe4cc40cbf8>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe4c368e438>
    │       └ <function BaseHandler.run at 0x7fe4cc409950>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4c2ca3550>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fe4cc409c80>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4c2ca3550>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4c2ca3550>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4c2ca3550>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               │    └ <function BaseHandler.get_response at 0x7fe4cc440e18>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-21/doc-778/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969ec80>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fe4c974c320>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969ebf8>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fe4c974c320>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fe4c974c6d8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969eb70>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fe4c974c6d8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fe4c974cb70>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969eae8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fe4c974cb70>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7fe4c96d8630>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969ea60>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7fe4c96d8630>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fe4c96d84e0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e9d8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fe4c96d84e0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fe4ca2c1ac8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e950>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fe4ca2c1ac8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fe4ca2c1978>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e8c8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fe4ca2c1978>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fe4ca2c1a20>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e6a8>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fe4ca2c1a20>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fe4cae86908>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e7b8>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fe4cae86908>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fe4ca2adb70>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               │    └ <function BaseHandler._get_response at 0x7fe4c969e730>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fe4ca2adb70>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 21, 'doc_id': 778}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-21/doc-778/'>
               └ <function doc at 0x7fe4ca1700d0>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 21, 'doc_id': 778}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-21/doc-778/'>
           └ <function doc at 0x7fe4ca170048>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 778
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fe4cc510b00>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 778, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fe4cd6cbd08>
                   └ <django.db.models.manager.Manager object at 0x7fe4cc411e80>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-06-27 06:35:21.064 | ERROR    | app_doc.views:doc:1075 - Collection browsing error
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe4d4679ea0>
    └ <Thread(Thread-5402, started daemon 140620488492800)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe4d4679c80>
    └ <Thread(Thread-5402, started daemon 140620488492800)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-5402, started daemon 140620488492800)>
    │    │        │    └ (<socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-5402, started daemon 140620488492800)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>>
    └ <Thread(Thread-5402, started daemon 140620488492800)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 43826)
    │    │              └ <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fe4cd612158>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
    │    │                   │        └ ('127.0.0.1', 43826)
    │    │                   └ <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fe4cc40e6a8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe4b02999b0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fe4cc40e730>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe4b02999b0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fe4cc40cbf8>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe4b02999b0>
    │       └ <function BaseHandler.run at 0x7fe4cc409950>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4c2ccbba8>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fe4cc409c80>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4c2ccbba8>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4c2ccbba8>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4c2ccbba8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │    └ <function BaseHandler.get_response at 0x7fe4cc440e18>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-21/doc-343/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969ec80>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fe4c974c320>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969ebf8>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fe4c974c320>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fe4c974c6d8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969eb70>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fe4c974c6d8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fe4c974cb70>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969eae8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fe4c974cb70>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7fe4c96d8630>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969ea60>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7fe4c96d8630>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fe4c96d84e0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e9d8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fe4c96d84e0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fe4ca2c1ac8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e950>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fe4ca2c1ac8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fe4ca2c1978>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e8c8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fe4ca2c1978>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fe4ca2c1a20>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e6a8>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fe4ca2c1a20>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fe4cae86908>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e7b8>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fe4cae86908>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fe4ca2adb70>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │    └ <function BaseHandler._get_response at 0x7fe4c969e730>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fe4ca2adb70>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 21, 'doc_id': 343}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <function doc at 0x7fe4ca1700d0>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 21, 'doc_id': 343}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-21/doc-343/'>
           └ <function doc at 0x7fe4ca170048>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 343
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fe4cc510b00>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 343, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fe4cd6cbd08>
                   └ <django.db.models.manager.Manager object at 0x7fe4cc411e80>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-06-27 10:10:35.801 | ERROR    | app_doc.views:doc:1075 - 文集浏览出错
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe4d4679ea0>
    └ <Thread(Thread-5561, started daemon 140620468270848)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe4d4679c80>
    └ <Thread(Thread-5561, started daemon 140620468270848)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-5561, started daemon 140620468270848)>
    │    │        │    └ (<socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-5561, started daemon 140620468270848)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>>
    └ <Thread(Thread-5561, started daemon 140620468270848)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 44680)
    │    │              └ <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fe4cd612158>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
    │    │                   │        └ ('127.0.0.1', 44680)
    │    │                   └ <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fe4cc40e6a8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe4b0287630>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fe4cc40e730>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe4b0287630>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fe4cc40cbf8>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe4b0287630>
    │       └ <function BaseHandler.run at 0x7fe4cc409950>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4c3e728d0>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fe4cc409c80>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4c3e728d0>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4c3e728d0>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4c3e728d0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │    └ <function BaseHandler.get_response at 0x7fe4cc440e18>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-26/doc-306/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969ec80>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fe4c974c320>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969ebf8>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fe4c974c320>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fe4c974c6d8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969eb70>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fe4c974c6d8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fe4c974cb70>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969eae8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fe4c974cb70>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7fe4c96d8630>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969ea60>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7fe4c96d8630>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fe4c96d84e0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e9d8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fe4c96d84e0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fe4ca2c1ac8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e950>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fe4ca2c1ac8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fe4ca2c1978>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e8c8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fe4ca2c1978>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fe4ca2c1a20>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e6a8>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fe4ca2c1a20>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fe4cae86908>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e7b8>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fe4cae86908>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fe4ca2adb70>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │    └ <function BaseHandler._get_response at 0x7fe4c969e730>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fe4ca2adb70>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 26, 'doc_id': 306}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <function doc at 0x7fe4ca1700d0>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 26, 'doc_id': 306}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-26/doc-306/'>
           └ <function doc at 0x7fe4ca170048>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 306
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fe4cc510b00>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 306, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fe4cd6cbd08>
                   └ <django.db.models.manager.Manager object at 0x7fe4cc411e80>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-06-27 13:52:17.092 | ERROR    | app_doc.views:doc:1075 - Collection browsing error
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe4d4679ea0>
    └ <Thread(Thread-5760, started daemon 140620496885504)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe4d4679c80>
    └ <Thread(Thread-5760, started daemon 140620496885504)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-5760, started daemon 140620496885504)>
    │    │        │    └ (<socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-5760, started daemon 140620496885504)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>>
    └ <Thread(Thread-5760, started daemon 140620496885504)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 45614)
    │    │              └ <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fe4cd612158>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
    │    │                   │        └ ('127.0.0.1', 45614)
    │    │                   └ <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fe4cc40e6a8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe4cd327080>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fe4cc40e730>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe4cd327080>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fe4cc40cbf8>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe4cd327080>
    │       └ <function BaseHandler.run at 0x7fe4cc409950>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4c2ca39e8>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fe4cc409c80>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4c2ca39e8>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4c2ca39e8>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4c2ca39e8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │    └ <function BaseHandler.get_response at 0x7fe4cc440e18>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-21/doc-273/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969ec80>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fe4c974c320>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969ebf8>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fe4c974c320>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fe4c974c6d8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969eb70>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fe4c974c6d8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fe4c974cb70>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969eae8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fe4c974cb70>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7fe4c96d8630>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969ea60>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7fe4c96d8630>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fe4c96d84e0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e9d8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fe4c96d84e0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fe4ca2c1ac8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e950>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fe4ca2c1ac8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fe4ca2c1978>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e8c8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fe4ca2c1978>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fe4ca2c1a20>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e6a8>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fe4ca2c1a20>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fe4cae86908>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e7b8>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fe4cae86908>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fe4ca2adb70>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │    └ <function BaseHandler._get_response at 0x7fe4c969e730>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fe4ca2adb70>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 21, 'doc_id': 273}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <function doc at 0x7fe4ca1700d0>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 21, 'doc_id': 273}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-21/doc-273/'>
           └ <function doc at 0x7fe4ca170048>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 273
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fe4cc510b00>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 273, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fe4cd6cbd08>
                   └ <django.db.models.manager.Manager object at 0x7fe4cc411e80>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-06-27 17:03:44.976 | ERROR    | app_doc.views:doc:1075 - Collection browsing error
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe4d4679ea0>
    └ <Thread(Thread-5847, started daemon 140620488492800)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe4d4679c80>
    └ <Thread(Thread-5847, started daemon 140620488492800)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-5847, started daemon 140620488492800)>
    │    │        │    └ (<socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-5847, started daemon 140620488492800)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>>
    └ <Thread(Thread-5847, started daemon 140620488492800)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 46278)
    │    │              └ <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fe4cd612158>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
    │    │                   │        └ ('127.0.0.1', 46278)
    │    │                   └ <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fe4cc40e6a8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe4c1bc60b8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fe4cc40e730>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe4c1bc60b8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fe4cc40cbf8>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe4c1bc60b8>
    │       └ <function BaseHandler.run at 0x7fe4cc409950>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4c3fd5be0>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fe4cc409c80>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4c3fd5be0>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4c3fd5be0>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4c3fd5be0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               │    └ <function BaseHandler.get_response at 0x7fe4cc440e18>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-21/doc-778/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969ec80>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fe4c974c320>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969ebf8>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fe4c974c320>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fe4c974c6d8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969eb70>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fe4c974c6d8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fe4c974cb70>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969eae8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fe4c974cb70>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7fe4c96d8630>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969ea60>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7fe4c96d8630>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fe4c96d84e0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e9d8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fe4c96d84e0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fe4ca2c1ac8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e950>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fe4ca2c1ac8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fe4ca2c1978>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e8c8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fe4ca2c1978>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fe4ca2c1a20>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e6a8>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fe4ca2c1a20>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fe4cae86908>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e7b8>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fe4cae86908>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fe4ca2adb70>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               │    └ <function BaseHandler._get_response at 0x7fe4c969e730>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fe4ca2adb70>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 21, 'doc_id': 778}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-21/doc-778/'>
               └ <function doc at 0x7fe4ca1700d0>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 21, 'doc_id': 778}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-21/doc-778/'>
           └ <function doc at 0x7fe4ca170048>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 778
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fe4cc510b00>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 778, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fe4cd6cbd08>
                   └ <django.db.models.manager.Manager object at 0x7fe4cc411e80>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
