2021-07-17 04:27:31.431 | ERROR    | app_doc.views:doc:1020 - 文集浏览出错
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f3a63f86378>
    └ <Thread(Thread-8806, started daemon 139888427005696)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f3a63f86158>
    └ <Thread(Thread-8806, started daemon 139888427005696)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-8806, started daemon 139888427005696)>
    │    │        │    └ (<socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-8806, started daemon 139888427005696)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7f3a5e030e48>>
    └ <Thread(Thread-8806, started daemon 139888427005696)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 13416)
    │    │              └ <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7f3a5db3de18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f3a5e030e48>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7f3a5e030e48>
    │    │                   │        └ ('127.0.0.1', 13416)
    │    │                   └ <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f3a5e030e48>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7f3a5cbe9b70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f3a5426ef28>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7f3a5cbe9bf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f3a5426ef28>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7f3a5cbe90d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7f3a5e030e48>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f3a5426ef28>
    │       └ <function BaseHandler.run at 0x7f3a5cbe1d90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f3a46199630>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7f3a5cbe6158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7f3a46199630>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7f3a46199630>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f3a575a29e8>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f3a46199630>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               │    └ <function BaseHandler.get_response at 0x7f3a5cd70840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f3a575a29e8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-22/doc-85/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7f3a55da2378>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f3a575a29e8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7f3a55dbd588>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f3a55da22f0>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7f3a55dbd588>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f3a55dbd828>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f3a55da2268>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f3a55dbd828>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7f3a55dc8be0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f3a55da21e0>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7f3a55dc8be0>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7f3a55dc87f0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f3a55da2158>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7f3a55dc87f0>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f3a574decf8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f3a55da20d0>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f3a574decf8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f3a569176a0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f3a55da2048>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f3a569176a0>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f3a569177b8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f3a55d8ef28>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f3a569177b8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f3a56917710>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f3a55d8eea0>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f3a56917710>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f3a56b99d68>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               │    └ <function BaseHandler._get_response at 0x7f3a55dee488>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f3a56b99d68>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7f3a575a29e8>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 22, 'doc_id': 85}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-22/doc-85/'>
               └ <function doc at 0x7f3a567c1048>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 22, 'doc_id': 85}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-22/doc-85/'>
           └ <function doc at 0x7f3a567bdf28>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 949, in doc
    project = Project.objects.get(id=int(pro_id))
              │       │                  └ 22
              │       └ <django.db.models.manager.ManagerDescriptor object at 0x7f3a5cce59e8>
              └ <class 'app_doc.models.Project'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 22}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7f3a5dc058c8>
                   └ <django.db.models.manager.Manager object at 0x7f3a55f8dd30>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Project'
    │    │     └ <Options for Project>
    │    └ <class 'app_doc.models.Project'>
    └ <QuerySet [<Project: About>, <Project: Algorithm Notebook>, <Project: Common Commands>, <Project: Machine Learning>, <Project...

app_doc.models.Project.DoesNotExist: Project matching query does not exist.
