2022-06-25 22:39:19.943 | ERROR    | app_doc.views:doc:1075 - 文集浏览出错
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe4d4679ea0>
    └ <Thread(Thread-4248, started daemon 140620506851072)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe4d4679c80>
    └ <Thread(Thread-4248, started daemon 140620506851072)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-4248, started daemon 140620506851072)>
    │    │        │    └ (<socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-4248, started daemon 140620506851072)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>>
    └ <Thread(Thread-4248, started daemon 140620506851072)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 35856)
    │    │              └ <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fe4cd612158>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
    │    │                   │        └ ('127.0.0.1', 35856)
    │    │                   └ <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fe4cc40e6a8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe4c1bc69e8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fe4cc40e730>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe4c1bc69e8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fe4cc40cbf8>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe4c1bc69e8>
    │       └ <function BaseHandler.run at 0x7fe4cc409950>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4c35c96a0>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fe4cc409c80>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4c35c96a0>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4c35c96a0>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4c35c96a0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               │    └ <function BaseHandler.get_response at 0x7fe4cc440e18>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-21/doc-777/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969ec80>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fe4c974c320>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969ebf8>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fe4c974c320>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fe4c974c6d8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969eb70>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fe4c974c6d8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fe4c974cb70>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969eae8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fe4c974cb70>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7fe4c96d8630>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969ea60>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7fe4c96d8630>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fe4c96d84e0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e9d8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fe4c96d84e0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fe4ca2c1ac8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e950>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fe4ca2c1ac8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fe4ca2c1978>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e8c8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fe4ca2c1978>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fe4ca2c1a20>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e6a8>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fe4ca2c1a20>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fe4cae86908>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e7b8>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fe4cae86908>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fe4ca2adb70>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               │    └ <function BaseHandler._get_response at 0x7fe4c969e730>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fe4ca2adb70>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 21, 'doc_id': 777}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-21/doc-777/'>
               └ <function doc at 0x7fe4ca1700d0>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 21, 'doc_id': 777}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-21/doc-777/'>
           └ <function doc at 0x7fe4ca170048>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 777
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fe4cc510b00>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 777, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fe4cd6cbd08>
                   └ <django.db.models.manager.Manager object at 0x7fe4cc411e80>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-06-26 06:01:07.570 | ERROR    | app_doc.views:doc:1075 - 文集浏览出错
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe4d4679ea0>
    └ <Thread(Thread-4469, started daemon 140620468270848)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe4d4679c80>
    └ <Thread(Thread-4469, started daemon 140620468270848)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-4469, started daemon 140620468270848)>
    │    │        │    └ (<socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-4469, started daemon 140620468270848)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>>
    └ <Thread(Thread-4469, started daemon 140620468270848)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 37622)
    │    │              └ <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fe4cd612158>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
    │    │                   │        └ ('127.0.0.1', 37622)
    │    │                   └ <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fe4cc40e6a8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe4b0322710>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fe4cc40e730>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe4b0322710>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fe4cc40cbf8>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe4b0322710>
    │       └ <function BaseHandler.run at 0x7fe4cc409950>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4c2c8ef98>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fe4cc409c80>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4c2c8ef98>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4c2c8ef98>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4c2c8ef98>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               │    └ <function BaseHandler.get_response at 0x7fe4cc440e18>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-21/doc-732/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969ec80>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fe4c974c320>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969ebf8>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fe4c974c320>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fe4c974c6d8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969eb70>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fe4c974c6d8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fe4c974cb70>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969eae8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fe4c974cb70>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7fe4c96d8630>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969ea60>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7fe4c96d8630>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fe4c96d84e0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e9d8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fe4c96d84e0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fe4ca2c1ac8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e950>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fe4ca2c1ac8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fe4ca2c1978>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e8c8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fe4ca2c1978>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fe4ca2c1a20>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e6a8>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fe4ca2c1a20>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fe4cae86908>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e7b8>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fe4cae86908>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fe4ca2adb70>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               │    └ <function BaseHandler._get_response at 0x7fe4c969e730>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fe4ca2adb70>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 21, 'doc_id': 732}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-21/doc-732/'>
               └ <function doc at 0x7fe4ca1700d0>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 21, 'doc_id': 732}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-21/doc-732/'>
           └ <function doc at 0x7fe4ca170048>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 732
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fe4cc510b00>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 732, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fe4cd6cbd08>
                   └ <django.db.models.manager.Manager object at 0x7fe4cc411e80>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-06-26 06:05:50.590 | ERROR    | app_doc.views:doc:1075 - 文集浏览出错
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe4d4679ea0>
    └ <Thread(Thread-4470, started daemon 140620468270848)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe4d4679c80>
    └ <Thread(Thread-4470, started daemon 140620468270848)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-4470, started daemon 140620468270848)>
    │    │        │    └ (<socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-4470, started daemon 140620468270848)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>>
    └ <Thread(Thread-4470, started daemon 140620468270848)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 37636)
    │    │              └ <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fe4cd612158>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
    │    │                   │        └ ('127.0.0.1', 37636)
    │    │                   └ <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fe4cc40e6a8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe4c2c7d208>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fe4cc40e730>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe4c2c7d208>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fe4cc40cbf8>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe4c2c7d208>
    │       └ <function BaseHandler.run at 0x7fe4cc409950>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4c2ca0f60>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fe4cc409c80>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4c2ca0f60>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4c2ca0f60>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4c2ca0f60>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               │    └ <function BaseHandler.get_response at 0x7fe4cc440e18>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-43/doc-775/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969ec80>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fe4c974c320>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969ebf8>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fe4c974c320>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fe4c974c6d8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969eb70>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fe4c974c6d8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fe4c974cb70>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969eae8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fe4c974cb70>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7fe4c96d8630>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969ea60>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7fe4c96d8630>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fe4c96d84e0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e9d8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fe4c96d84e0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fe4ca2c1ac8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e950>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fe4ca2c1ac8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fe4ca2c1978>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e8c8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fe4ca2c1978>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fe4ca2c1a20>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e6a8>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fe4ca2c1a20>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fe4cae86908>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e7b8>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fe4cae86908>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fe4ca2adb70>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               │    └ <function BaseHandler._get_response at 0x7fe4c969e730>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fe4ca2adb70>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 43, 'doc_id': 775}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-43/doc-775/'>
               └ <function doc at 0x7fe4ca1700d0>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 43, 'doc_id': 775}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-43/doc-775/'>
           └ <function doc at 0x7fe4ca170048>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 775
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fe4cc510b00>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 775, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fe4cd6cbd08>
                   └ <django.db.models.manager.Manager object at 0x7fe4cc411e80>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-06-26 10:59:30.939 | ERROR    | app_doc.views:doc:1075 - Collection browsing error
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe4d4679ea0>
    └ <Thread(Thread-4639, started daemon 140620468270848)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe4d4679c80>
    └ <Thread(Thread-4639, started daemon 140620468270848)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-4639, started daemon 140620468270848)>
    │    │        │    └ (<socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-4639, started daemon 140620468270848)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>>
    └ <Thread(Thread-4639, started daemon 140620468270848)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 39192)
    │    │              └ <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fe4cd612158>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
    │    │                   │        └ ('127.0.0.1', 39192)
    │    │                   └ <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fe4cc40e6a8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe4b0314630>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fe4cc40e730>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe4b0314630>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fe4cc40cbf8>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe4b0314630>
    │       └ <function BaseHandler.run at 0x7fe4cc409950>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4b0314278>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fe4cc409c80>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4b0314278>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4b0314278>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4b0314278>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-790/'>
               │    └ <function BaseHandler.get_response at 0x7fe4cc440e18>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-21/doc-790/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969ec80>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-790/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fe4c974c320>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-790/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969ebf8>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fe4c974c320>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-790/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fe4c974c6d8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-790/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969eb70>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fe4c974c6d8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-790/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fe4c974cb70>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-790/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969eae8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fe4c974cb70>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-790/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7fe4c96d8630>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-790/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969ea60>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7fe4c96d8630>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-790/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fe4c96d84e0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-790/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e9d8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fe4c96d84e0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-790/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fe4ca2c1ac8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-790/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e950>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fe4ca2c1ac8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-790/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fe4ca2c1978>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-790/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e8c8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fe4ca2c1978>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-790/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fe4ca2c1a20>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-790/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e6a8>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fe4ca2c1a20>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-790/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fe4cae86908>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-790/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e7b8>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fe4cae86908>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-790/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fe4ca2adb70>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-790/'>
               │    └ <function BaseHandler._get_response at 0x7fe4c969e730>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fe4ca2adb70>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-790/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 21, 'doc_id': 790}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-21/doc-790/'>
               └ <function doc at 0x7fe4ca1700d0>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 21, 'doc_id': 790}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-21/doc-790/'>
           └ <function doc at 0x7fe4ca170048>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 790
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fe4cc510b00>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 790, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fe4cd6cbd08>
                   └ <django.db.models.manager.Manager object at 0x7fe4cc411e80>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-06-26 11:25:05.472 | ERROR    | app_doc.views:doc:1075 - 文集浏览出错
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe4d4679ea0>
    └ <Thread(Thread-4649, started daemon 140620496885504)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe4d4679c80>
    └ <Thread(Thread-4649, started daemon 140620496885504)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-4649, started daemon 140620496885504)>
    │    │        │    └ (<socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-4649, started daemon 140620496885504)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>>
    └ <Thread(Thread-4649, started daemon 140620496885504)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 39268)
    │    │              └ <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fe4cd612158>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
    │    │                   │        └ ('127.0.0.1', 39268)
    │    │                   └ <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fe4cc40e6a8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe4c3604198>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fe4cc40e730>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe4c3604198>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fe4cc40cbf8>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe4c3604198>
    │       └ <function BaseHandler.run at 0x7fe4cc409950>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4c2c927f0>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fe4cc409c80>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4c2c927f0>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4c2c927f0>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4c2c927f0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │    └ <function BaseHandler.get_response at 0x7fe4cc440e18>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-21/doc-738/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969ec80>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fe4c974c320>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969ebf8>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fe4c974c320>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fe4c974c6d8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969eb70>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fe4c974c6d8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fe4c974cb70>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969eae8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fe4c974cb70>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7fe4c96d8630>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969ea60>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7fe4c96d8630>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fe4c96d84e0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e9d8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fe4c96d84e0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fe4ca2c1ac8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e950>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fe4ca2c1ac8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fe4ca2c1978>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e8c8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fe4ca2c1978>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fe4ca2c1a20>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e6a8>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fe4ca2c1a20>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fe4cae86908>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e7b8>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fe4cae86908>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fe4ca2adb70>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │    └ <function BaseHandler._get_response at 0x7fe4c969e730>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fe4ca2adb70>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 21, 'doc_id': 738}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <function doc at 0x7fe4ca1700d0>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 21, 'doc_id': 738}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-21/doc-738/'>
           └ <function doc at 0x7fe4ca170048>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 738
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fe4cc510b00>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 738, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fe4cd6cbd08>
                   └ <django.db.models.manager.Manager object at 0x7fe4cc411e80>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-06-26 14:05:51.381 | ERROR    | app_doc.views:doc:1075 - 文集浏览出错
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe4d4679ea0>
    └ <Thread(Thread-4961, started daemon 140620488492800)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe4d4679c80>
    └ <Thread(Thread-4961, started daemon 140620488492800)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-4961, started daemon 140620488492800)>
    │    │        │    └ (<socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-4961, started daemon 140620488492800)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>>
    └ <Thread(Thread-4961, started daemon 140620488492800)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 40282)
    │    │              └ <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fe4cd612158>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
    │    │                   │        └ ('127.0.0.1', 40282)
    │    │                   └ <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fe4cc40e6a8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe4c3e866d8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fe4cc40e730>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe4c3e866d8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fe4cc40cbf8>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe4cdd60f28>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe4c3e866d8>
    │       └ <function BaseHandler.run at 0x7fe4cc409950>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4c3e86208>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fe4cc409c80>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4c3e86208>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4c3e86208>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fe4c3e86208>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-286/'>
               │    └ <function BaseHandler.get_response at 0x7fe4cc440e18>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-1/doc-286/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969ec80>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-286/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fe4c974c320>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-286/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969ebf8>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fe4c974c320>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-286/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fe4c974c6d8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-286/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969eb70>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fe4c974c6d8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-286/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fe4c974cb70>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-286/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969eae8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fe4c974cb70>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-286/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7fe4c96d8630>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-286/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969ea60>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7fe4c96d8630>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-286/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fe4c96d84e0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-286/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e9d8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fe4c96d84e0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-286/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fe4ca2c1ac8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-286/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e950>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fe4ca2c1ac8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-286/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fe4ca2c1978>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-286/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e8c8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fe4ca2c1978>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-286/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fe4ca2c1a20>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-286/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e6a8>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fe4ca2c1a20>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-286/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fe4cae86908>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-286/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe4c969e7b8>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fe4cae86908>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-286/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fe4ca2adb70>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-286/'>
               │    └ <function BaseHandler._get_response at 0x7fe4c969e730>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fe4ca2adb70>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-286/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fe4caf45978>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 1, 'doc_id': 286}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-1/doc-286/'>
               └ <function doc at 0x7fe4ca1700d0>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 1, 'doc_id': 286}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-1/doc-286/'>
           └ <function doc at 0x7fe4ca170048>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 286
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fe4cc510b00>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 286, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fe4cd6cbd08>
                   └ <django.db.models.manager.Manager object at 0x7fe4cc411e80>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
